export const weatherInfo = {
    "-50--15": {
        day: {
            image: "extreme-freeze.png",
            alt: "Extreme freezing cold (Day)",
            note: "Dangerously cold ❄️. Stay indoors if possible!",
        },
        night: {
            image: "extreme-freeze-night.jpg",
            alt: "Extreme freezing cold (Night)",
            note: "Freezing night ❄️. Stay warm and avoid going out!",
        },
    },
    "-15--10": {
        day: {
            image: "very-cold.png",
            alt: "Very cold weather (Day)",
            note: "Very cold! Dress in layers and cover up.",
        },
        night: {
            image: "very-cold-night.jpg",
            alt: "Very cold weather (Night)",
            note: "Very cold night 🌙. Extra blankets recommended.",
        },
    },
    "-10--5": {
        day: {
            image: "cold.png",
            alt: "Cold temperature (Day)",
            note: "Cold weather, wear a warm jacket.",
        },
        night: {
            image: "cold-night.jpg",
            alt: "Cold temperature (Night)",
            note: "Chilly night, wear thick clothes to stay warm.",
        },
    },
    "-5-0": {
        day: {
            image: "chilly.png",
            alt: "Chilly near freezing (Day)",
            note: "Chilly, gloves and hats recommended.",
        },
        night: {
            image: "chilly-night.jpg",
            alt: "Chilly near freezing (Night)",
            note: "Cold night near freezing ❄️. Keep warm indoors.",
        },
    },
    "0-5": {
        day: {
            image: "cool.png",
            alt: "Cool temperature (Day)",
            note: "Cool weather. Light jacket needed.",
        },
        night: {
            image: "cool-night.jpg",
            alt: "Cool temperature (Night)",
            note: "Cool night, keep a blanket handy.",
        },
    },
    "5-10": {
        day: {
            image: "mild-cool.png",
            alt: "Mildly cool (Day)",
            note: "Mildly cool, a sweater should be fine.",
        },
        night: {
            image: "mild-cool-night.jpg",
            alt: "Mildly cool (Night)",
            note: "Slightly cold night, sweater or light blanket recommended.",
        },
    },
    "10-15": {
        day: {
            image: "pleasant.png",
            alt: "Pleasant weather (Day)",
            note: "Pleasant and fresh, great for a walk outside.",
        },
        night: {
            image: "pleasant-night.jpg",
            alt: "Pleasant weather (Night)",
            note: "Comfortable evening, perfect for a night stroll.",
        },
    },
    "15-20": {
        day: {
            image: "warm.png",
            alt: "Warm weather (Day)",
            note: "Mildly cool 🌤️. Feels nice and a bit fresh outside.",
        },
        night: {
            image: "warm-night.jpg",
            alt: "Warm weather (Night)",
            note: "Cool night 🌙. A sweater or blanket may be needed.",
        },
    },
    "20-25": {
        day: {
            image: "comfortably-warm.png",
            alt: "Comfortably warm (Day)",
            note: "Nice and warm, perfect for outdoor activities.",
        },
        night: {
            image: "comfortably-warm-night.jpg",
            alt: "Comfortably warm (Night)",
            note: "Warm night 🌙. A light breeze keeps it nice.",
        },
    },
    "25-30": {
        day: {
            image: "hot.png",
            alt: "Hot temperature (Day)",
            note: "Hot weather 🌞, stay hydrated.",
        },
        night: {
            image: "hot-night.jpg",
            alt: "Hot temperature (Night)",
            note: "Warm night, keep hydrated and cool.",
        },
    },
    "30-35": {
        day: {
            image: "very-hot.png",
            alt: "Very hot weather (Day)",
            note: "Very hot! Avoid being outside too long.",
        },
        night: {
            image: "very-hot-night.jpg",
            alt: "Very hot weather (Night)",
            note: "Hot evening 🌙. Use fans or AC to stay cool.",
        },
    },
    "35-50": {
        day: {
            image: "extreme-heat.png",
            alt: "Extreme heat (Day)",
            note: "Extreme heat 🌋. Stay cool and drink lots of water!",
        },
        night: {
            image: "extreme-heat-night.jpg",
            alt: "Extreme heat (Night)",
            note: "Very hot night 🌙. Avoid heavy activities and stay hydrated.",
        },
    },
};

export const rainInfo = {
    "0-1": {
        day: {
            image: "light-rain.png",
            alt: "Light rain (Day)",
            note: "Drizzle ☔. A light umbrella is enough.",
        },
        night: {
            image: "light-rain-night.jpg",
            alt: "Light rain (Night)",
            note: "Light showers 🌧️. Roads may be a little slippery.",
        },
    },
    "1-5": {
        day: {
            image: "moderate-rain.png",
            alt: "Moderate rain (Day)",
            note: "Moderate rain ☔. Take a proper umbrella or raincoat.",
        },
        night: {
            image: "moderate-rain-night.jpg",
            alt: "Moderate rain (Night)",
            note: "Steady rainfall 🌧️. Drive carefully.",
        },
    },
    "5-20": {
        day: {
            image: "heavy-rain.png",
            alt: "Heavy rain (Day)",
            note: "Heavy rain 🌧️. Stay safe, possible waterlogging.",
        },
        night: {
            image: "heavy-rain-night.jpg",
            alt: "Heavy rain (Night)",
            note: "Strong rainfall 🌧️. Avoid unnecessary travel.",
        },
    },
    "20-100": {
        day: {
            image: "extreme-rain.png",
            alt: "Extreme rain (Day)",
            note: "Extreme rain ⛈️. Flooding possible, stay indoors!",
        },
        night: {
            image: "extreme-rain-night.jpg",
            alt: "Extreme rain (Night)",
            note: "Dangerous rainfall ⛈️. Avoid going outside.",
        },
    },
};

export const cities = [
    // A
    "Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad", "Kunduz", "Lashkar Gah", "Taloqan", "Pul-e Khumri", "Ghazni",
    "Faizabad", "Khost", "Gardez", "Bamyan", "Charikar", "Shiberghan", "Asadabad", "Aibak", "Baghlan", "Mahmud-e Raqi",
    "Mehtarlam", "Qalat", "Zaranj", "Farah", "Chaghcharan", "Nili", "Tarinkot", "Qala-e Naw", "Parun", "Maidan Shahr",
    "Bazarak", "Panjshir", "Sharana", "Spin Boldak", "Gereshk", "Nad Ali", "Sangin", "Musa Qala", "Kajaki", "Marjah",
    "Helmand", "Uruzgan", "Daikundi", "Ghor", "Badghis", "Faryab", "Jawzjan", "Sar-e Pol", "Balkh", "Samangan",
    "Baghlan", "Takhar", "Badakhshan", "Nuristan", "Laghman", "Nangarhar", "Kunar", "Kapisa", "Parwan", "Wardak",
    "Logar", "Ghazni", "Paktika", "Paktia", "Khost", "Zabul", "Kandahar", "Helmand", "Nimroz", "Farah",
    "Herat", "Badghis", "Faryab", "Jawzjan", "Sar-e Pol", "Balkh", "Samangan", "Baghlan", "Kunduz", "Takhar",
    "Badakhshan", "Panjshir", "Kapisa", "Parwan", "Kabul", "Wardak", "Logar", "Ghazni", "Paktika", "Paktia",
    "Khost", "Nangarhar", "Laghman", "Kunar", "Nuristan", "Bamyan", "Daikundi", "Ghor", "Uruzgan", "Zabul",
    "Tirana", "Durrës", "Vlorë", "Shkodër", "Fier", "Korçë", "Elbasan", "Berat", "Lushnjë", "Kavajë",
    "Gjirokastër", "Sarandë", "Laç", "Kukës", "Lezhë", "Pogradec", "Patos", "Krujë", "Kuçovë", "Burrel",
    "Cërrik", "Ballsh", "Mamurras", "Gramsh", "Peqin", "Bilisht", "Himarë", "Divjakë", "Delvinë", "Selenicë",
    "Roskovec", "Libohovë", "Memaliaj", "Bajram Curri", "Bulqizë", "Maliq", "Koplik", "Poliçan", "Përmet",
    "Ersekë", "Kamëz", "Vorë", "Rrogozhinë", "Shijak", "Pukë", "Finiq", "Konispol", "Tepelenë", "Këlcyrë",
    "Dropull", "Libohova", "Leskovik", "Kolonjë", "Devoll", "Malësi e Madhe", "Vau i Dejës", "Mirditë", "Mat", "Dibër",
    "Bulqizë", "Librazhd", "Prrenjas", "Belsh", "Mallakastër", "Lushnje", "Fier", "Divjakë", "Roskovec", "Patos",
    "Ballsh", "Vlorë", "Himarë", "Delvinë", "Sarandë", "Konispol", "Finiq", "Dropull", "Gjirokastër", "Përmet",
    "Këlcyrë", "Tepelenë", "Memaliaj", "Libohova", "Leskovik", "Kolonjë", "Devoll", "Korçë", "Pogradec", "Maliq",
    "Bilisht", "Ersekë", "Librazhd", "Prrenjas", "Gramsh", "Elbasan", "Peqin", "Cërrik", "Belsh", "Berat",
    "Algiers", "Oran", "Constantine", "Batna", "Djelfa", "Sétif", "Annaba", "Sidi Bel Abbès", "Biskra", "Tébessa",
    "Tiaret", "Béjaïa", "Tlemcen", "Ouargla", "Skikda", "Mostaganem", "M'Sila", "Oum El Bouaghi", "Chlef", "Médéa",
    "Tizi Ouzou", "El Oued", "Khenchela", "Souk Ahras", "Mascara", "Relizane", "Saïda", "Laghouat", "Bordj Bou Arréridj", "Bouira",
    "Tamanrasset", "Tissemsilt", "Jijel", "Guelma", "Ain Defla", "Naama", "Ain Témouchent", "Ghardaïa", "El Bayadh", "Illizi",
    "Bordj Badji Mokhtar", "Béni Abbès", "Timimoun", "Ouled Djellal", "In Salah", "In Guezzam", "Touggourt", "Djanet", "El M'Ghair", "El Meniaa",
    "Blida", "Boumerdès", "Tipaza", "Ain Benian", "Zeralda", "El Achir", "Bou Ismail", "Koléa", "Cherchell", "Hadjout",
    "Larbaâ", "Boufarik", "Larbaa", "Meftah", "Ouled Yaïch", "Bougara", "Chiffa", "El Affroun", "Hammam Melouane", "Oued Alleug",
    "Soumaa", "Ben Khellil", "Guerrouaou", "Ouled Slama", "Bir Ghbalou", "Sour El Ghozlane", "Ain Bessem", "Bechloul", "El Hakimia", "Dirah",
    "El Adjiba", "Haizer", "El Esnam", "Ridane", "Bir El Ater", "Ouenza", "El Kouif", "Negrine", "Ferkane", "El Houidjbet",
    "Bekkaria", "Stah Guentis", "El Mezeraa", "Youkous", "Zeribet El Oued", "Kais", "El Mahmal", "Tamlouka", "Ibn Ziad", "Ouled Hamla",
    "Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria", "La Massana", "Santa Coloma d'Andorra", "Ordino", "El Pas de la Casa", "Soldeu", "Canillo",
    "Arinsal", "Pal", "La Cortinada", "Llorts", "El Serrat", "Anyós", "Bixessarri", "Fontaneda", "Nagol", "Aixàs",
    "Juberri", "Certers", "Llumeneres", "Ransol", "El Tarter", "Grau Roig", "Pessons", "Incles", "Meritxell", "Els Plans",
    "Aixovall", "Borda", "Vila", "Mas de Ribafeta", "L'Aldosa", "Engolasters", "Les Bons", "Prats", "Sispony", "Anyós",
    "Segudet", "Molleres", "Escàs", "Mas d'Alins", "Cortals d'Encamp", "Grau dels Cortals", "Pla de l'Estany", "Els Cortals", "Ransol", "Bordes d'Envalira",
    "Coll d'Ordino", "Pic de Casamanya", "Pic del Comapedrosa", "Estanys de Tristaina", "Sorteny", "La Rabassa", "Naturlandia", "Erts", "La Margineda", "Santa Coloma",
    "Pont de la Tosca", "Andorra Park Hotel", "Caldea", "Madriu-Perafita-Claror", "Casa de la Vall", "Pont de Paris", "Pont d'Engordany", "Pont de la Margineda", "Roc d'Enclar", "Sant Joan de Caselles",
    "Santa Coloma Church", "Sant Esteve Church", "Sant Andreu Church", "Sant Martí Church", "Sant Miquel Church", "Sant Climent Church", "Sant Romà Church", "Santa Eulàlia Church", "Sant Serni Church", "Sant Cristòfol Church",
    "Casa Rull", "Casa d'Areny-Plandolit", "Museu Nacional de l'Automòbil", "Museu del Perfum", "Museu Postal", "Centre de Natura de la Cortinada", "Interpretació de la Natura", "Museu de la Miniatura", "Museu del Còmic", "Museu Carmen Thyssen",
    "Palau de Gel", "Complex Esportiu Serradells", "Camp de Futbol d'Andorra", "Estadi Comunal", "Centre Esportiu dels Serradells", "Piscines Comunals", "Palau d'Esports", "Tennis Club Vallnord", "Club de Golf", "Escola Esquí Soldeu",
    "Luanda", "Huambo", "Lobito", "Benguela", "Kuito", "Lubango", "Malanje", "Namibe", "Soyo", "Cabinda",
    "Uíge", "Saurimo", "Sumbe", "Menongue", "Lucapa", "Caxito", "Kuando Kubango", "Ondjiva", "N'dalatando", "M'banza-Kongo",
    "Dundo", "Tombua", "Porto Amboim", "Camabatela", "Caluquembe", "Chibia", "Matala", "Quilengues", "Humpata", "Gambos",
    "Cahama", "Cuvelai", "Namacunde", "Ombadja", "Cuanhama", "Calai", "Curoca", "Cuangar", "Rivungo", "Dirico",
    "Mavinga", "Cuchi", "Cuemba", "Longa", "Bailundo", "Cachiungo", "Londuimbali", "Mungo", "Chicala-Cholohanga", "Caála",
    "Longonjo", "Ekunha", "Alto Hama", "Chitembo", "Katabola", "Ukuma", "Tchicala-Tcholoanga", "Bocoio", "Chongoroi", "Ganda",
    "Porto Amboim", "Balombo", "Baía Farta", "Catumbela", "Cubal", "Caimbambo", "Chongoroi", "Ganda", "Bocoio", "Balombo",
    "Camacupa", "Cangandala", "Caombo", "Cahombo", "Cacuso", "Kiwaba Nzogi", "Luquembo", "Marimba", "Massango", "Mucari",
    "Quela", "Quirima", "Calandula", "Kunda-dia-Base", "Lemba", "Lucala", "Ngonguembo", "Xa-Muteba", "Banga", "Pango Aluquém",
    "Kambundi-Catembo", "Kaombo", "Songo", "Kiuaba", "Milando", "Alto Cuilo", "Cuango", "Xá-Muteba", "Lubalo", "Chitato",
    "St. John's", "All Saints", "Liberta", "Potter's Village", "Bolans", "Swetes", "Parham", "English Harbour", "Falmouth", "Willikies",
    "Piggotts", "Five Islands", "Jennings", "Cedar Grove", "Freetown", "Old Road", "Johnson's Point", "Urlings", "Bendals", "Dickenson Bay",
    "Runaway Bay", "Hodges Bay", "Crosbies", "Barnes Hill", "Yorks", "Villa", "Gambles", "Buckleys", "Sea View Farm", "Newfield",
    "Bethesda", "Crab Hill", "John Hughes", "Marble Hill", "McNish Mountain", "Orange Valley", "Paynters", "Richland Park", "Tomlinson",
    "Barbuda", "Codrington", "Dulcina", "Spanish Point", "Goat Island", "Bird Island", "Long Island", "Green Island", "Great Bird Island", "Hell's Gate",
    "Two Foot Bay", "Palmetto Point", "Coco Point", "River Landing", "Low Bay", "Pink Sand Beach", "Castle Hill", "Darby Cave", "Indian Town",
    "Martello Tower", "The Caves", "Frigate Bird Sanctuary", "Cedar Tree Point", "Highland House", "Barbuda Highlands", "Codrington Lagoon", "Gravenor Bay", "Rubbish Bay",
    "Devil's Bridge", "Betty's Hope", "Shirley Heights", "Nelson's Dockyard", "Clarence House", "Dow's Hill", "Fig Tree Drive", "Rendezvous Bay", "Half Moon Bay", "Long Bay",
    "Darkwood Beach", "Ffryes Beach", "Valley Church Beach", "Jolly Beach", "Hawksbill Beach", "Eden Island", "Rat Island", "Maiden Island", "Redhead Island", "York Island",
    "Crump Island", "Rabbit Island", "Pelican Island", "Lobster Island", "Sandy Island", "Deep Bay", "Five Islands Harbour", "Nonsuch Bay", "Indian Creek", "Willoughby Bay",
    "Buenos Aires", "Córdoba", "Rosario", "Mendoza", "San Miguel de Tucumán", "La Plata", "Mar del Plata", "Salta", "Santa Fe", "San Juan",
    "Resistencia", "Neuquén", "Santiago del Estero", "Corrientes", "Posadas", "Bahía Blanca", "Paraná", "Formosa", "San Luis", "La Rioja",
    "Catamarca", "Río Gallegos", "Santa Rosa", "San Salvador de Jujuy", "Ushuaia", "San Rafael", "Tandil", "Río Cuarto", "Comodoro Rivadavia", "Concordia",
    "San Nicolás de los Arroyos", "San Fernando del Valle de Catamarca", "Quilmes", "Lanús", "General San Martín", "Lomas de Zamora", "Almirante Brown", "Merlo", "Morón", "Tigre",
    "Malvinas Argentinas", "San Isidro", "Esteban Echeverría", "La Matanza", "Florencio Varela", "Berazategui", "Avellaneda", "Vicente López", "Tres de Febrero", "Hurlingham",
    "Ituzaingó", "José C. Paz", "San Fernando", "Escobar", "Ezeiza", "Pilar", "Moreno", "General Rodríguez", "Luján", "Mercedes",
    "Chivilcoy", "Pergamino", "Junín", "Azul", "Olavarría", "Pehuajó", "Trenque Lauquen", "Bolívar", "Balcarce", "Necochea",
    "Tres Arroyos", "Coronel Suárez", "Pigüé", "General Villegas", "Carlos Casares", "Lincoln", "25 de Mayo", "Bragado", "Chacabuco", "Salto",
    "Arrecifes", "San Pedro", "Baradero", "Zárate", "Campana", "San Antonio de Areco", "Carmen de Areco", "Capitán Sarmiento", "Rojas", "Colón",
    "Pergamino", "San Nicolás", "Ramallo", "San Lorenzo", "Puerto San Martín", "Fray Luis Beltrán", "Villa Gobernador Gálvez", "Pérez", "Granadero Baigorria", "Capitán Bermúdez",
    "Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan", "Abovyan", "Kapan", "Armavir", "Gavar", "Artashat",
    "Goris", "Ashtarak", "Sevan", "Charentsavan", "Dilijan", "Ijevan", "Alaverdi", "Kajaran", "Masis", "Ararat",
    "Sisian", "Yeghegnadzor", "Tashir", "Spitak", "Vardenis", "Berd", "Noyemberyan", "Chambarak", "Tumanyan", "Akhtala",
    "Metsamor", "Artik", "Maralik", "Aparan", "Talin", "Vedi", "Nor Hachn", "Jermuk", "Tsaghkadzor", "Arzni",
    "Agarak", "Meghri", "Dastakert", "Shahumyan", "Nor Kharberd", "Lchashen", "Martuni", "Getashen", "Sarukhan", "Lichk",
    "Dzoraghp", "Artsvaberd", "Khachik", "Garni", "Bjni", "Aghveran", "Meghradzor", "Arzakan", "Byureghavan", "Lusagyugh",
    "Aragats", "Sasunik", "Oshakan", "Voskevaz", "Parpi", "Ashtarak", "Ushi", "Karmrashen", "Aygek", "Aygavan",
    "Irind", "Yeghipatrush", "Kaqavaberd", "Akunq", "Aghdzk", "Arakelots", "Shirakamut", "Pemzashen", "Fioletovo", "Arevashat",
    "Lernahovit", "Hovtashen", "Tsaghkashen", "Anipemza", "Arevabuyr", "Aragatsavan", "Berdashen", "Dzoraghp", "Hoktemberyan", "Hartagyugh",
    "Lernarot", "Antaramej", "Hartavan", "Mrgavet", "Noravan", "Arzakan", "Tsaghkunk", "Aghtsk", "Garnahovit", "Burastan",
    "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Newcastle", "Canberra", "Wollongong", "Logan City",
    "Geelong", "Hobart", "Townsville", "Cairns", "Toowoomba", "Darwin", "Launceston", "Ballarat", "Bendigo", "Albury",
    "Mandurah", "Latrobe City", "Mackay", "Rockhampton", "Bunbury", "Bundaberg", "Wagga Wagga", "Hervey Bay", "Mildura", "Shepparton",
    "Port Macquarie", "Gladstone", "Tamworth", "Traralgon", "Orange", "Dubbo", "Geraldton", "Nowra", "Warrnambool", "Bathurst",
    "Warragul", "Kalgoorlie", "Devonport", "Mount Gambier", "Lismore", "Nelson Bay", "Moe", "Alice Springs", "Wodonga", "Sunbury",
    "Melton", "Maryborough", "Cranbourne", "Frankston", "Pakenham", "Craigieburn", "Werribee", "Dandenong", "Casey", "Whittlesea",
    "Hume", "Wyndham", "Monash", "Knox", "Maroondah", "Whitehorse", "Boroondara", "Glen Eira", "Stonnington", "Port Phillip",
    "Yarra", "Melbourne", "Banyule", "Darebin", "Moreland", "Moonee Valley", "Maribyrnong", "Hobsons Bay", "Brimbank", "Melton",
    "Macedon Ranges", "Mitchell", "Mornington Peninsula", "Cardinia", "Bass Coast", "South Gippsland", "Baw Baw", "Wellington", "East Gippsland", "Towong",
    "Alpine", "Indigo", "Wangaratta", "Benalla", "Strathbogie", "Mansfield", "Murrindindi", "Nillumbik", "Yarra Ranges", "Surf Coast",
    "Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Sankt Pölten", "Dornbirn",
    "Wiener Neustadt", "Steyr", "Feldkirch", "Bregenz", "Leonding", "Klosterneuburg", "Baden", "Wolfsberg", "Leoben", "Krems",
    "Traun", "Amstetten", "Kapfenberg", "Mödling", "Hallein", "Kufstein", "Traiskirchen", "Schwechat", "Braunau am Inn", "Stockerau",
    "Saalfelden", "Ansfelden", "Tulln", "Hohenems", "Spittal an der Drau", "Telfs", "Ternitz", "Perchtoldsdorf", "Hall in Tirol", "Lustenau",
    "Sankt Veit an der Glan", "Gmunden", "Wörgl", "Schwaz", "Hard", "Vöcklabruck", "Lienz", "Rankweil", "Hollabrunn", "Enns",
    "Brunn am Gebirge", "Ried im Innkreis", "Bad Ischl", "Götzis", "Sankt Johann im Pongau", "Gänserndorf", "Bischofshofen", "Eisenstadt", "Mistelbach", "Waidhofen an der Ybbs",
    "Korneuburg", "Neunkirchen", "Groß-Enzersdorf", "Seekirchen am Wallersee", "Sankt Andrä", "Steyregg", "Eugendorf", "Grödig", "Wals-Siezenheim", "Bergheim",
    "Götzendorf an der Leitha", "Himberg", "Fischamend", "Gerasdorf bei Wien", "Deutsch-Wagram", "Ebreichsdorf", "Guntramsdorf", "Laxenburg", "Achau", "Maria Enzersdorf",
    "Henndorf am Wallersee", "Oberndorf bei Salzburg", "Eugendorf", "Elsbethen", "Koppl", "Fuschl am See", "Sankt Gilgen", "Strobl", "Mondsee", "Innerschwand am Mondsee",
    "Zell am See", "Mittersill", "Tamsweg", "Sankt Michael im Lungau", "Radstadt", "Altenmarkt im Pongau", "Flachau", "Wagrain", "Sankt Johann im Pongau", "Schwarzach im Pongau",
    "Baku", "Ganja", "Sumqayit", "Mingachevir", "Qazax", "Shirvan", "Shaki", "Yevlax", "Lankaran", "Nakhchivan",
    "Shamakhi", "Quba", "Ismayilli", "Agdam", "Fuzuli", "Jabrayil", "Zangilan", "Qubadli", "Lachin", "Shusha",
    "Khankendi", "Aghdam", "Tartar", "Barda", "Beylagan", "Imishli", "Sabirabad", "Saatli", "Hajigabul", "Kurdamir",
    "Aghjabadi", "Zardab", "Ujar", "Goychay", "Agdash", "Qabala", "Oghuz", "Shaki", "Zagatala", "Qax",
    "Balakan", "Qusar", "Khachmaz", "Shabran", "Siyazan", "Davachi", "Quba", "Gusar", "Khizi", "Sumqayit",
    "Absheron", "Khirdalan", "Mardakan", "Bilgah", "Nardaran", "Pirallahi", "Ramany", "Sabunchu", "Surakhani", "Yasamal",
    "Nasimi", "Narimanov", "Nizami", "Binagadi", "Khatai", "Sabail", "Pirallahi", "Qaradag", "Sadarak", "Ordubad",
    "Julfa", "Babak", "Sharur", "Kangarli", "Shahbuz", "Culfa", "Masalli", "Yardimli", "Jalilabad", "Lerik",
    "Astara", "Bilasuvar", "Neftchala", "Salyan", "Ali Bayramli", "Shirvan", "Hajigabul", "Gobustan", "Madrasa", "Shamakhi",
    "Aghsu", "Ismayilli", "Qabala", "Oghuz", "Shaki", "Zagatala", "Qax", "Balakan", "Qusar", "Khachmaz",

    // B
    "Nassau", "Freeport", "West End", "Coopers Town", "Marsh Harbour", "Dunmore Town", "Rock Sound", "Tarpum Bay", "Governor's Harbour", "Spanish Wells",
    "Clarence Town", "Simms", "Deadman's Cay", "Colonel Hill", "Duncan Town", "Kemps Bay", "Fresh Creek", "Nicholls Town", "Mangrove Cay", "Lowe Sound",
    "High Rock", "McLean's Town", "Sweeting's Cay", "Fox Town", "Pine Ridge", "Eight Mile Rock", "Lucaya", "Hawksbill Creek", "Pelican Point", "Gold Rock Creek",
    "Water Cay", "Smith Point", "Holmes Rock", "Bahama Terrace", "Seagrape", "Fortune Beach", "Coral Harbour", "Adelaide", "Carmichael", "Yellow Elder",
    "Montagu", "Fort Charlotte", "Cable Beach", "Goodman's Bay", "Delaporte", "South Beach", "Eastern Road", "Paradise Island", "Potter's Cay", "Arawak Cay",
    "Fox Hill", "Sandilands", "Stapledon Gardens", "Bain Town", "Grants Town", "Centerville", "Palmdale", "Kennedy", "Golden Gates", "Yamacraw",
    "Sea Breeze", "Elizabeth Estates", "Garden Hills", "Pinewood Gardens", "Golden Isles", "Coral Heights", "Blair", "Millennium Gardens", "Fire Trail", "Robinson Road",
    "Soldier Road", "Wulff Road", "Thompson Boulevard", "Blue Hill Road", "Mackey Street", "Bay Street", "Shirley Street", "Meeting Street", "East Street", "West Street",
    "North Street", "South Street", "Village Road", "Prince Charles Drive", "JFK Drive", "Independence Drive", "Tonique Williams Highway", "Sir Milo Butler Highway", "Gladstone Road", "Market Street",
    "Parliament Street", "George Street", "Frederick Street", "Charlotte Street", "Augusta Street", "Marlborough Street", "Delancy Street", "Cockburn Street", "Duke Street", "Hill Street",
    "Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali", "Isa Town", "Sitra", "Budaiya", "Jidhafs", "Al-Malikiyah",
    "Sanabis", "Tubli", "Barbar", "Sar", "Galali", "Janabiyah", "Zallaq", "Askar", "Diraz", "Karbabad",
    "Sanad", "Nuwaidrat", "Khamis", "Jaw", "Dur", "Hawar", "Umm Na'san", "Sakhir", "Awali", "Alba",
    "Hidd", "Dair", "Qalali", "Ma'ameer", "Damistan", "Sadad", "Karranah", "Mahazza", "Salihiya", "Jasra",
    "Busaiteen", "Qudaibiya", "Jannusan", "Nabih Saleh", "Salmabad", "East Riffa", "West Riffa", "North Riffa", "South Riffa", "Riffa Views",
    "Amwaj Islands", "Reef Island", "Durrat Al Bahrain", "Diyar Al Muharraq", "Dilmunia Island", "Bahrain Bay", "Seef District", "Diplomatic Area", "Adliya", "Juffair",
    "Hoora", "Gudaibiya", "Zinj", "Segaiya", "Um Al Hassam", "Mahooz", "Salmaniya", "Naim", "Khobar", "Exhibition Road",
    "Manama Souq", "Gold Souq", "Bab Al Bahrain", "Government Avenue", "King Faisal Highway", "Shaikh Salman Highway", "Shaikh Khalifa Bin Salman Highway", "Shaikh Isa Bin Salman Highway", "Al Fateh Highway", "Diplomatic Area",
    "Financial Harbour", "World Trade Center", "Bahrain International Circuit", "Al Areen Wildlife Park", "Tree of Life", "Qal'at al-Bahrain", "Bahrain National Museum", "Al Fateh Mosque", "Ahmed Al Fateh Islamic Center", "Royal Golf Club",
    "Bahrain International Airport", "King Fahd Causeway", "University of Bahrain", "Arabian Gulf University", "Bahrain Polytechnic", "Applied Science University", "Ahlia University", "Gulf University", "Royal University for Women", "Bahrain Institute of Banking",
    "Dhaka", "Chittagong", "Sylhet", "Khulna", "Rajshahi", "Rangpur", "Barisal", "Mymensingh", "Comilla", "Narayanganj",
    "Gazipur", "Bogra", "Jessore", "Dinajpur", "Pabna", "Faridpur", "Kushtia", "Tangail", "Jamalpur", "Kishoreganj",
    "Manikganj", "Munshiganj", "Narsingdi", "Gopalganj", "Madaripur", "Shariatpur", "Rajbari", "Brahmanbaria", "Lakshmipur", "Chandpur",
    "Feni", "Noakhali", "Cox's Bazar", "Bandarban", "Rangamati", "Khagrachari", "Patuakhali", "Pirojpur", "Jhalokati", "Barguna",
    "Bhola", "Satkhira", "Narail", "Magura", "Jhenaidah", "Chuadanga", "Meherpur", "Chapai Nawabganj", "Natore", "Sirajganj",
    "Joypurhat", "Naogaon", "Thakurgaon", "Panchagarh", "Nilphamari", "Lalmonirhat", "Kurigram", "Gaibandha", "Sherpur", "Netrokona",
    "Habiganj", "Moulvibazar", "Sunamganj", "Savar", "Tongi", "Dhamrai", "Keraniganj", "Dohar", "Nawabganj", "Singair",
    "Mirzapur", "Kalihati", "Sakhipur", "Basail", "Madhupur", "Ghatail", "Gopalpur", "Delduar", "Nagarpur", "Bhaluka",
    "Trishal", "Muktagachha", "Dhobaura", "Phulpur", "Haluaghat", "Gouripur", "Ishwarganj", "Nandail", "Tarakanda", "Fulbaria",
    "Gaffargaon", "Valuka", "Sarishabari", "Jaydebpur", "Kaliakair", "Kapasia", "Sripur", "Kaliganj", "Maiganj", "Itna",
    "Bridgetown", "Speightstown", "Oistins", "Bathsheba", "Holetown", "Crane", "Six Cross Roads", "Belleplaine", "Blackmans", "Bulkeley",
    "Cane Garden", "Checker Hall", "Cleland", "Codrington", "College Savannah", "Diamond Corner", "Drax Hall", "Ellerton", "Fairfield", "Four Cross Roads",
    "Gall Hill", "Gibson Corner", "Glebe", "Goodland", "Gun Hill", "Hampton", "Haynesville", "Holders Hill", "Horse Hill", "Jackson",
    "Joes River", "Kendal", "Lamberts", "Lancaster", "Lower Carlton", "Mapps", "Mile and a Quarter", "Mount Brevitor", "Mullins", "Newton",
    "Oldbury", "Parish Land", "Pie Corner", "Porters", "Prior Park", "Rock Hall", "Saint George", "Saint Lawrence", "Sandy Lane", "Sargeants Village",
    "Sealy Hall", "Shop Hill", "Simond", "Staple Grove", "Sweet Vale", "The Whim", "Top Rock", "Turners Hall Woods", "Valley", "Wanstead",
    "Warrens", "Welches", "Wellington", "West Terrace", "Westmoreland", "White Hall", "Worthing", "Christ Church", "Saint James", "Saint John",
    "Saint Joseph", "Saint Lucy", "Saint Michael", "Saint Peter", "Saint Philip", "Saint Thomas", "Saint Andrew", "Boarded Hall", "Clifton Hall", "Endeavour",
    "Fitts Village", "Friendship", "Hothersal Turning", "Indian Ground", "Jackson Bay", "Kingsland", "Long Bay", "Melvin Hill", "Pie Corner", "Quick Step",
    "Ragged Point", "Saint Patricks", "Sandford", "Silver Hill", "Thicket", "Venture", "Wanstead", "Westbury", "White Hill", "Workman's",
    "Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest", "Bobruisk", "Baranovichi", "Borisov", "Pinsk",
    "Orsha", "Mozyr", "Novopolotsk", "Lida", "Soligorsk", "Molodechno", "Polotsk", "Zhlobin", "Svetlogorsk", "Rechitsa",
    "Slutsk", "Kobrin", "Volkovysk", "Kalinkavičy", "Slonim", "Rogachev", "Zhodino", "Osipovichi", "Maryina Gorka", "Smorgon",
    "Nesvizh", "Dzerzhinsk", "Fanipol", "Logoisk", "Stolbtsy", "Kletsk", "Uzda", "Kopyl", "Cherven", "Berezino",
    "Krupki", "Smolevichi", "Pleshchenitsy", "Borisov", "Vileyka", "Dokshitsy", "Postavy", "Sharkovshchina", "Braslav", "Miory",
    "Glubokoe", "Polotsk", "Verkhnyadzvinsk", "Haradok", "Lepel", "Chashniki", "Senno", "Tolochin", "Kruhlaye", "Dubrovno",
    "Liozno", "Beshenkovichi", "Ushachi", "Vitebsk", "Orsha", "Shumilino", "Rossony", "Verkhnedvinsk", "Gorodok", "Sholkovo",
    "Chechersk", "Vetka", "Dobrush", "Korma", "Zhitkovichi", "Loyew", "Brahin", "Khoiniki", "Narovlya", "Yelsk",
    "Bykhov", "Krichev", "Klimovichi", "Kostyukovichi", "Khotsimsk", "Cherikov", "Dribin", "Kirovsk", "Belynichi", "Gorki",
    "Shklov", "Mogilev", "Mstislavl", "Slavgorod", "Krasnoselski", "Glusk", "Osipovichi", "Pukhovichi", "Soligorsk", "Starye Dorogi",
    "Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons", "Aalst",
    "Mechelen", "La Louvière", "Kortrijk", "Hasselt", "Sint-Niklaas", "Ostend", "Tournai", "Genk", "Seraing", "Roeselare",
    "Mouscron", "Verviers", "Dendermonde", "Beringen", "Turnhout", "Vilvoorde", "Lokeren", "Sint-Truiden", "Herstal", "Brasschaat",
    "Grimbergen", "Mol", "Maasmechelen", "Waregem", "Ypres", "Lier", "Mortsel", "Geraardsbergen", "Herentals", "Sint-Pieters-Leeuw",
    "Geel", "Schoten", "Wavre", "Edegem", "Kapellen", "Wilrijk", "Kalmthout", "Tessenderlo", "Zaventem", "Lommel",
    "Halle", "Westerlo", "Zoersel", "Brasschaat", "Duffel", "Aartselaar", "Ranst", "Boechout", "Wijnegem", "Wommelgem",
    "Borsbeek", "Mortsel", "Hove", "Lint", "Kontich", "Waarloos", "Boom", "Niel", "Schelle", "Hemiksem",
    "Rumst", "Temse", "Bornem", "Puurs", "Sint-Amands", "Willebroek", "Klein-Willebroek", "Tisselt", "Hingene", "Waasmunster",
    "Beveren", "Sint-Gillis-Waas", "Stekene", "Sint-Pauwels", "Kemzeke", "Haasdonk", "Kieldrecht", "Verrebroek", "Vrasene", "Melsele",
    "Zwijndrecht", "Burcht", "Kruibeke", "Bazel", "Temse", "Elversele", "Steendorp", "Tielrode", "Bornem", "Mariekerke",
    "Belize City", "San Ignacio", "Orange Walk", "Dangriga", "Corozal", "Punta Gorda", "San Pedro", "Caye Caulker", "Hopkins", "Placencia",
    "Benque Viejo del Carmen", "Spanish Lookout", "Ladyville", "Belmopan", "Burrell Boom", "Crooked Tree", "Maskall", "Sarteneja", "Chunox", "Little Belize",
    "San Antonio", "Cristo Rey", "Santa Elena", "Succotz", "Georgeville", "Central Farm", "Unitedville", "Santa Familia", "Calla Creek", "Camalote",
    "Valley of Peace", "Blackman Eddy", "Double Head Cabbage", "Roaring Creek", "Teakettle", "Ontario", "Esperanza", "Armenia", "More Tomorrow", "Franks Eddy",
    "San Jose Succotz", "Bullet Tree Falls", "Arenal", "San Antonio", "Cristo Rey", "Santa Elena", "Duck Run", "Macaw Bank", "Branch Mouth", "Billy White",
    "Trial Farm", "Iguana Creek", "Augustine", "Eldridgeville", "Cotton Tree", "Never Delay", "Gracy Rock", "San Joaquin", "St. Margaret", "Patchacan",
    "Lemonal", "Shipyard", "Trial Farm", "Louisville", "Revenge", "Calcutta", "San Carlos", "Guinea Grass", "San Felipe", "Indian Creek",
    "San Estevan", "Yo Creek", "August Pine Ridge", "Blue Creek", "Progresso", "San Jose", "San Pablo", "Trial Farm", "Douglas", "San Roman",
    "Santa Cruz", "San Victor", "Libertad", "Chan Pine Ridge", "Trinidad", "Richmond Hill", "Fire Burn", "San Lazaro", "Santa Rita", "Consejo",
    "Copper Bank", "Cerro Hill", "Patchakan", "Calcutta", "San Andres", "Carolina", "Xaibe", "Ranchito", "Paraiso", "Louisville",
    "Cotonou", "Porto-Novo", "Parakou", "Djougou", "Bohicon", "Kandi", "Abomey", "Natitingou", "Lokossa", "Ouidah",
    "Savalou", "Pobè", "Dogbo", "Kétou", "Sakété", "Allada", "Aplahoué", "Dassa-Zoumé", "Bembèrèkè", "Nikki",
    "Malanville", "Ségbana", "Banikoara", "Kalalé", "Pèrèrè", "N'Dali", "Tchaourou", "Kouandé", "Tanguiéta", "Matéri",
    "Cobly", "Boukoumbé", "Toucountouna", "Kérou", "Péhunco", "Sinendé", "Bétérou", "Glazoué", "Ouessé", "Savé",
    "Bassila", "Copargo", "Djidja", "Za-Kpota", "Agbangnizoun", "Covè", "Ouinhi", "Zangnanado", "Zogbodomey", "Abomey-Calavi",
    "Sô-Ava", "Toffo", "Zè", "Kpomassè", "Tori-Bossito", "Djakotomey", "Lalo", "Toviklin", "Agoué", "Come",
    "Houéyogbé", "Bopa", "Athiémé", "Klouékanmè", "Adjarra", "Adjohoun", "Aguégués", "Akpro-Missérété", "Avrankou", "Bonou",
    "Dangbo", "Sèmè-Kpodji", "Ifangni", "Adja-Ouèrè", "Kétou", "Pobè", "Sakété", "Akpro-Missérété", "Adjarra", "Avrankou",
    "Bonou", "Dangbo", "Ouinhi", "Zangnanado", "Zogbodomey", "Abomey-Calavi", "Allada", "Kpomassè", "Ouidah", "Sô-Ava",
    "Toffo", "Torori-Bossito", "Zè", "Aplahoué", "Djakotomey", "Dogbo", "Klouékanmè", "Lalo", "Toviklin", "Lokossa",
    "Thimphu", "Phuntsholing", "Punakha", "Wangdue Phodrang", "Jakar", "Trashigang", "Mongar", "Pemagatshel", "Samdrup Jongkhar", "Gelephu",
    "Trongsa", "Gasa", "Haa", "Samtse", "Chhukha", "Dagana", "Tsirang", "Sarpang", "Zhemgang", "Lhuentse",
    "Paro", "Bajo", "Drugyel Dzong", "Rinpung Dzong", "Tashichho Dzong", "Simtokha Dzong", "Dechencholing", "Motithang", "Kawajangsa", "Lungten Zampa",
    "Babesa", "Changzamtog", "Zilukha", "Taba", "Olakha", "Hejo", "Pangbisa", "Dechencholing", "Motithang", "Kawajangsa",
    "Centenary Farmers Market", "Weekend Market", "Clock Tower Square", "Memorial Chorten", "Buddha Dordenma", "Tashichho Dzong", "National Memorial Chorten", "Changangkha Lhakhang", "Simtokha Dzong", "Dechenphu Lhakhang",
    "Phajoding", "Tango Monastery", "Cheri Monastery", "Dechen Phodrang", "Pangri Zampa", "Tashigang", "Wangduecholing Palace", "Chorten Kora", "Trashi Yangtse", "Khoma",
    "Bomdila", "Radi", "Bartsham", "Rangjung", "Yurung", "Kanglung", "Khaling", "Gomtu", "Phongmey", "Shongphu",
    "Lhuntse Dzong", "Khoma", "Kurtoe", "Jarey", "Gangzur", "Menbi", "Tsenkhar", "Bumthang", "Ura", "Tang",
    "Choekhor", "Chumey", "Kurjey Lhakhang", "Jambay Lhakhang", "Tamshing Lhakhang", "Konchogsum Lhakhang", "Thangbi Lhakhang", "Ngang Lhakhang", "Ogyen Choling", "Lhodrak Kharchhu",
    "Mongar Dzong", "Drametse", "Kengkhar", "Gyalpoizhing", "Chaskar Gewog", "Jurmey", "Kuri Gewog", "Ngatshang", "Saleng", "Silambi",
    "La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Potosí", "Tarija", "Oruro", "Trinidad", "Cobija", "Riberalta",
    "Guayaramerín", "Yacuiba", "Villazón", "Bermejo", "Camiri", "Warnes", "Montero", "El Alto", "Quillacollo", "Sacaba",
    "Tiquipaya", "Colcapirhua", "Vinto", "Sipe Sipe", "Punata", "Tarata", "Cliza", "Totora", "Pocona", "Chimoré",
    "Villa Tunari", "Puerto Villarroel", "Entre Ríos", "Shinahota", "Ivirgarzama", "San Carlos", "Todos Santos", "Isinuta", "Pasorapa", "Aiquile",
    "Mizque", "Vila Vila", "Alalay", "Capinota", "Sicaya", "Toko", "San Benito", "Arbieto", "Santivañez", "Tolata",
    "Llallagua", "Catavi", "Siglo XX", "Uncía", "Chayanta", "Colquechaca", "Macha", "Pocoata", "Ocurí", "Toro Toro",
    "San Pedro de Buena Vista", "Acasio", "Caripuyo", "Arampampa", "Vitichi", "Ravelo", "Betanzos", "Chaqui", "Caiza D", "Cotagaita",
    "Tupiza", "Atocha", "Quechisla", "Colcha K", "San Pablo de Lípez", "San Antonio de Esmoruco", "Llica", "Tahua", "Colchani", "Uyuni",
    "Challapata", "Huanuni", "Machacamarca", "Poopó", "Pazña", "Antequera", "Eucaliptus", "Caracollo", "Sora Sora", "Curahuara de Carangas",
    "Turco", "Corque", "Choque Cota", "Santiago de Machaca", "Catacora", "Cruz de Machacamarca", "Santiago de Callapa", "Charaña", "Nazacara de Pacajes", "Caquiaviri",
    "Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Bijeljina", "Brčko", "Bihać", "Prijedor", "Trebinje",
    "Doboj", "Cazin", "Velika Kladuša", "Visoko", "Goražde", "Konjic", "Gradiška", "Bosanska Krupa", "Märkische Heide", "Živinice",
    "Lukavac", "Gradačac", "Bosanski Brod", "Orašje", "Derventa", "Bosanski Novi", "Foča", "Gacko", "Nevesinje", "Čapljina",
    "Stolac", "Ljubuški", "Grude", "Široki Brijeg", "Posušje", "Tomislavgrad", "Livno", "Bugojno", "Jajce", "Travnik",
    "Novi Travnik", "Vitez", "Busovača", "Kiseljak", "Kreševo", "Fojnica", "Kakanj", "Vareš", "Breza", "Olovo",
    "Ilijaš", "Hadžići", "Ilidža", "Vogošća", "Pale", "Sokolac", "Rogatica", "Višegrad", "Čajniče", "Pljevlja",
    "Užice", "Priboj", "Nova Varoš", "Sjenica", "Tutin", "Novi Pazar", "Raška", "Vranje", "Leskovac", "Niš",
    "Zaječar", "Bor", "Majdanpek", "Negotin", "Kladovo", "Golubac", "Veliko Gradište", "Požarevac", "Smederevo", "Mladenovac",
    "Sopot", "Lazarevac", "Obrenovac", "Valjevo", "Loznica", "Šabac", "Ruma", "Sremska Mitrovica", "Inđija", "Stara Pazova",
    "Pećinci", "Irig", "Beočin", "Srbobran", "Temerin", "Bečej", "Novi Bečej", "Žitište", "Sečanj", "Kikinda",
    "Gaborone", "Francistown", "Molepolole", "Serowe", "Selibe Phikwe", "Maun", "Kanye", "Mochudi", "Mahalapye", "Palapye",
    "Tlokweng", "Gabane", "Jwaneng", "Lobatse", "Ramotswa", "Letlhakeng", "Moshupa", "Thamaga", "Kopong", "Mmopane",
    "Mogoditshane", "Phakalane", "Broadhurst", "Gaborone West", "Old Naledi", "Block 6", "Block 7", "Block 8", "Block 9", "Block 10",
    "Sebele", "Mogoditshane", "Tlokweng", "Gabane", "Mmopane", "Kopong", "Thamaga", "Moshupa", "Letlhakeng", "Ramotswa",
    "Otse", "Mogobane", "Digawana", "Ramatlabama", "Lobatse", "Barolong", "Goodhope", "Struizendam", "Manyana", "Kanye",
    "Molepolole", "Gabane", "Kopong", "Thamaga", "Moshupa", "Letlhakeng", "Mmankgodi", "Jwaneng", "Kokotsha", "Sese",
    "Mabutsane", "Lehututu", "Ukwi", "Hukuntsi", "Lokgwabe", "Werda", "Bokspits", "Tshabong", "Khawa", "Middlepits",
    "Kang", "Ghanzi", "Ncojane", "Charles Hill", "D'Kar", "New Xade", "Kuke", "Bere", "East Hanahai", "Groot Laagte",
    "Maun", "Sehithwa", "Gumare", "Shakawe", "Mohembo", "Seronga", "Beetsha", "Jao", "Tubu", "Nxamasere",
    "Kasane", "Kazungula", "Pandamatenga", "Lesoma", "Chobe", "Kavimba", "Kachikau", "Mabele", "Satau", "Parakarungu",
    "São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Goiânia",
    "Belém", "Porto Alegre", "Guarulhos", "Campinas", "São Luís", "São Gonçalo", "Maceió", "Duque de Caxias", "Nova Iguaçu", "Teresina",
    "Natal", "Osasco", "Campo Grande", "Santo André", "João Pessoa", "Jaboatão dos Guararapes", "Contagem", "São Bernardo do Campo", "Uberlândia", "Sorocaba",
    "Aracaju", "Feira de Santana", "Cuiabá", "Joinville", "Aparecida de Goiânia", "Ribeirão Preto", "Juiz de Fora", "Londrina", "Niterói", "Ananindeua",
    "Belford Roxo", "Caxias do Sul", "Campos dos Goytacazes", "Macapá", "Vila Velha", "São João de Meriti", "Florianópolis", "Santos", "Serra", "Betim",
    "Diadema", "Jundiaí", "Carapicuíba", "Piracicaba", "Cariacica", "Bauru", "Mauá", "Canoas", "Boa Vista", "Olinda",
    "São José dos Campos", "Paulista", "Caucaia", "Blumenau", "Petrópolis", "Praia Grande", "Pelotas", "Itaquaquecetuba", "Rio Branco", "Suzano",
    "Ponta Grossa", "Anápolis", "Maringá", "Franca", "Vitória", "Caruaru", "Montes Claros", "Foz do Iguaçu", "Taubaté", "Uberaba",
    "Imperatriz", "Gravataí", "Embu das Artes", "Taboão da Serra", "Sumaré", "Barueri", "Várzea Grande", "Limeira", "Rio das Ostras", "Novo Hamburgo",
    "Presidente Prudente", "Santa Maria", "Americana", "Jacareí", "Araraquara", "Hortolândia", "Marília", "Magé", "Indaiatuba", "Cotia",
    "São Vicente", "Itabuna", "Pindamonhangaba", "Itapevi", "Ferraz de Vasconcelos", "Atibaia", "Francisco Morato", "Ribeirão das Neves", "Rio Verde", "Governador Valadares",
    "Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar", "Pekan Tutong", "Lumapas", "Gadong", "Kiulap", "Berakas",
    "Jerudong", "Muara", "Serasa", "Mentiri", "Tungku", "Sengkurong", "Lambak", "Rimba", "Subok", "Kota Batu",
    "Pengkalan Batu", "Mulaut", "Panchor Murai", "Salar", "Perpindahan Tanjung Bunut", "Kilugos", "Bukit Panggal", "Keriam", "Tanjong Nangka", "Kampong Ayer",
    "Kampong Saba", "Kampong Burong Pingai Ayer", "Kampong Tamoi Tengah", "Kampong Bolkiah", "Kampong Sungai Kedayan", "Kampong Pengiran Siraja Muda", "Kampong Dato Gandi", "Kampong Kiarong",
    "Kampong Anggerek Desa", "Kampong Beribi", "Kampong Jangsak", "Kampong Mata-Mata", "Kampong Perpindahan Mata-Mata", "Kampong Bengkurong", "Kampong Lumapas", "Kampong Bunut",
    "Kampong Perpindahan Bunut", "Kampong Junjongan", "Kampong Sg Tilong", "Kampong Kulapis", "Kampong Menglait", "Kampong Mabohai", "Kampong Katok", "Kampong Kiudang",
    "Kampong Tanah Jambu", "Kampong Sungai Hanching", "Kampong Burong Pingai Ayer", "Kampong Tamoi Ujong", "Kampong Peramu", "Kampong Setia Negara", "Kampong Sungai Kebun",
    "Kampong Salambigar", "Kampong Wasan", "Kampong Birau", "Kampong Bebatik Kilanas", "Kampong Telisai", "Kampong Rambai", "Kampong Ukong", "Kampong Panchong",
    "Kampong Benutan", "Kampong Bukit Udal", "Kampong Pengkalan Sibabau", "Kampong Long Mayan", "Kampong Belait", "Kampong Suri", "Kampong Lumut", "Kampong Melilas",
    "Kampong Labi", "Kampong Teraja", "Kampong Rampayoh", "Kampong Sukang", "Kampong Buau", "Kampong Mendaram", "Kampong Ulu Mendaram", "Kampong Bang", "Kampong Labu Estate", "Kampong Liang",
    "Kampong Bakiau", "Kampong Danau", "Kampong Kerong", "Kampong Parit", "Kampong Serambangun", "Kampong Selangan", "Kampong Tali Air", "Kampong Benali", "Kampong Bintudoh", "Kampong Layong",
    "Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Sliven", "Dobrich", "Shumen",
    "Pernik", "Haskovo", "Yambol", "Pazardzhik", "Blagoevgrad", "Veliko Tarnovo", "Vratsa", "Gabrovo", "Asenovgrad", "Vidin",
    "Kazanlak", "Kyustendil", "Kardzhali", "Montana", "Dimitrovgrad", "Targovishte", "Lovech", "Silistra", "Dupnitsa", "Svishtov",
    "Razgrad", "Gorna Oryahovitsa", "Smolyan", "Petrich", "Sandanski", "Samokov", "Sevlievo", "Lom", "Karlovo", "Velingrad",
    "Nova Zagora", "Troyan", "Aytos", "Botevgrad", "Gotse Delchev", "Peshtera", "Harmanli", "Karnobat", "Panagyurishte", "Chirpan",
    "Popovo", "Rakovski", "Radnevo", "Svilengrad", "Aksakovo", "Devnya", "Provadia", "Beloslav", "Byala", "Dolni Chiflik",
    "Kavarna", "Balchik", "Shabla", "Krushari", "General Toshevo", "Tervel", "Alfatar", "Silistra", "Tutrakan", "Dulovo",
    "Ruse", "Vetovo", "Tsenovo", "Ivanovo", "Borovo", "Slivo Pole", "Nikolaevo", "Dve Mogili", "Tsar Kaloyan", "Kubrat",
    "Razgrad", "Zavet", "Loznitsa", "Samuil", "Isperih", "Novi Pazar", "Tsar Kaloyan", "Kubrat", "Zavet", "Loznitsa",
    "Targovishte", "Opaka", "Popovo", "Antonovo", "Omurtag", "Shumen", "Kaspichan", "Novi Pazar", "Venets", "Smyadovo",
    "Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora", "Kaya", "Tenkodogo", "Orodara", "Fada N'gourma", "Gaoua",
    "Dori", "Gorom-Gorom", "Djibo", "Bogandé", "Diapaga", "Gayéri", "Pama", "Kantchari", "Matiacoali", "Namoungou",
    "Bittou", "Zabré", "Garango", "Pouytenga", "Koupéla", "Boulsa", "Kongoussi", "Tikaré", "Séguénéga", "Gourcy",
    "Yako", "Koumbri", "Ouindigui", "Sollé", "Thiou", "Pilimpikou", "Titao", "Sabcé", "Barga", "Gomponsom",
    "Manga", "Pô", "Kombissiri", "Tangaye", "Réo", "Kyon", "Boussé", "Zorgho", "Sapouy", "Léo",
    "Saponé", "Silly", "Cassou", "Kokologho", "Nanoro", "Soaw", "Didyr", "Pabré", "Loumbila", "Ziniaré",
    "Koubri", "Dapelogo", "Saaba", "Baskouré", "Zitenga", "Dablo", "Mané", "Rouko", "Bourzanga", "Boussouma",
    "Tougouri", "Zéguédéguin", "Pibaore", "Silmiougou", "Rollo", "Sommiaga", "Gomborko", "Namissiguima", "Rapadama", "Tikare",
    "Rambo", "Siglé", "Bouroum", "Korsimoro", "Pissila", "Sanmatenga", "Dablo", "Boussouma", "Bourzanga", "Mané",
    "Pensa", "Ziga", "Bam", "Nasséré", "Zimtenga", "Rouko", "Tikaré", "Namissiguima", "Bouroum", "Kaya",
    "Bujumbura", "Gitega", "Muyinga", "Ngozi", "Ruyigi", "Kayanza", "Bururi", "Makamba", "Muramvya", "Cankuzo",
    "Cibitoke", "Bubanza", "Karusi", "Rutana", "Kirundo", "Mwaro", "Rumonge", "Isale", "Buhiga", "Bukirasazi",
    "Bugendana", "Giheta", "Gishubi", "Itaba", "Makebuko", "Mutaho", "Ryansoro", "Butaganzwa", "Musigati", "Murwi",
    "Mabayi", "Rugombo", "Mpanda", "Buganda", "Gihanga", "Vyanda", "Bisoro", "Bugabira", "Bwambarangwe", "Ntega",
    "Busoni", "Giteranyi", "Kirundo", "Vumbi", "Bugabira", "Busiga", "Ntega", "Busoni", "Giteranyi", "Vumbi",
    "Ruhororo", "Nyabikere", "Gashoho", "Gatara", "Gashikanwa", "Kayanza", "Kabarore", "Matongo", "Muhanga", "Rango",
    "Bukeye", "Muruta", "Bugenyuzi", "Gihogazi", "Gitaramuka", "Mutumba", "Nyabihanga", "Rusaka", "Shombo", "Buhinyuza",
    "Mishiha", "Mwakiro", "Nyarusange", "Ruyigi", "Cankuzo", "Cendajuru", "Gisagara", "Kigamba", "Kinyinya", "Barunda",
    "Vyerwa", "Songa", "Mugina", "Gisozi", "Marangara", "Mukike", "Musongati", "Rusengo", "Butaganzwa", "Buhiga",
    "Bukirasazi", "Bugendana", "Giheta", "Gishubi", "Itaba", "Makebuko", "Mutaho", "Ryansoro", "Gitega", "Bugarama",

    // C
    "Praia", "Mindelo", "Santa Maria", "Assomada", "Porto Novo", "Espargos", "Ribeira Grande", "Tarrafal", "São Filipe", "Mosteiros",
    "Pedra Badejo", "Cidade Velha", "Calheta", "Paul", "Ponta do Sol", "Ribeira Brava", "Nova Sintra", "Furna", "Vila da Ribeira Brava", "Sal Rei",
    "Povoação Velha", "Cabeçalinho", "João Teves", "Achada Monte", "Palmarejo", "Tira Chapéu", "Plateau", "Fazenda", "Achada Santo António", "Safende",
    "Calabaceira", "São Domingos", "Rui Vaz", "Achada Igreja", "Picos", "Orgãos", "Ribeira da Prata", "Chã de Tanque", "Flamengos", "Fajã d'Água",
    "Cova Figueira", "Fajãzinha", "Ribeira do Paul", "Janela", "Pombas", "Ribeira da Cruz", "Coculi", "Passagem", "Ribeira da Torre", "Vila das Pombas",
    "Chã das Caldeiras", "Campanas Baixo", "Relva", "Monte Grande", "Corvo", "Tinteira", "Igreja", "Figueira das Naus", "Achada Furna", "Monte Vermelho",
    "Calhau", "Fontainhas", "Ponta do Norte", "Cruzinha", "Palmeira", "Pedra de Lume", "Buracona", "Terra Boa", "Algodoeiro", "Feijoal",
    "Murdeira", "Kite Beach", "Monte Leão", "Ponta Preta", "Vila do Maio", "Morro", "Pedro Vaz", "Calheta do Maio", "Barreiro", "Cascabulho",
    "Pilão Cão", "Figueira da Horta", "Porto Cais", "Ribeira Dom João", "Alcatraz", "Água das Penas", "Monte Batalha", "Lombo Branco", "Lombo de Figueira", "Porto Mosquito",
    "Alto Mira", "Bela Vista", "Lombo Tanque", "Achada Lém", "Paúl", "Ribeirão", "Carvoeiros", "Eito", "Chã João Vaz", "Pico da Cruz",
    "Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Poipet", "Kampong Cham", "Pursat", "Kampong Chhnang", "Kratie", "Kampong Speu",
    "Kampong Thom", "Kampot", "Stung Treng", "Prey Veng", "Takeo", "Svay Rieng", "Banteay Meanchey", "Kep", "Pailin", "Mondulkiri",
    "Ratanakiri", "Preah Vihear", "Oddar Meanchey", "Koh Kong", "Tboung Khmum", "Sisophon", "Bavet", "Kampong Saom", "Kampong Trabek", "Kampong Kdei",
    "Bati", "Doun Kaev", "Kampong Rou", "Samraong", "Anlong Veng", "Paoy Pet", "Malai", "Thmar Puok", "Ou Chrov", "Preah Netr Preah",
    "Serei Saophoan", "Svay Chek", "Banteay Ampil", "Preah Sdach", "Kompong Svay", "Santuk", "Stoung", "Prasat Balangk", "Prasat Sambour", "Baray",
    "Kampong Tralach", "Kampong Leaeng", "Rolea B'ier", "Tuek Phos", "Chol Kiri", "Boribo", "Krakor", "Phnum Kravanh", "Veal Veng", "Bakan",
    "Kandieng", "Rukhak Kiri", "Phsa Pou", "Ta Sanh", "Romeas Haek", "Romduol", "Kampong Trabaek", "Peam Chor", "Peam Ro", "Preaek Prasab",
    "Ba Phnum", "Kamchay Mear", "Kanhchriech", "Kampong Leav", "Me Sang", "Neak Loeung", "Peam Chor", "Preah Sdach", "Kampong Trabaek", "Sithor Kandal",
    "Ang Tasom", "Bati", "Bourei Cholsar", "Kiri Vong", "Prey Kabbas", "Samraong", "Tram Kak", "Treang", "Doun Kaev", "Kirivong",
    "Chantrea", "Chbar Mon", "Dambae", "Kampong Trach", "Touk Meas", "Banteay Meas", "Bokor", "Chhuk", "Kampot", "Tuek Chhou",
    "Yaoundé", "Douala", "Garoua", "Bamenda", "Maroua", "Bafoussam", "Ngaoundéré", "Bertoua", "Loum", "Kumba",
    "Nkongsamba", "Buea", "Limbe", "Edéa", "Tiko", "Kribi", "Dschang", "Mbalmayo", "Ebolowa", "Sangmélima",
    "Foumban", "Bafang", "Mbouda", "Bandjoun", "Bangangté", "Mokolo", "Kousséri", "Guider", "Mora", "Wum",
    "Fundong", "Kumbo", "Ndop", "Bali", "Bafut", "Tubah", "Santa", "Jakiri", "Nkambe", "Misaje",
    "Muyuka", "Idenau", "Mundemba", "Ekondo Titi", "Nguti", "Konye", "Tombel", "Alou", "Bangem", "Fontem",
    "Mamfe", "Eyumojock", "Akwaya", "Upper Bayang", "Tinto", "Lebialem", "Wabane", "Alou", "Fontem", "Fokoué",
    "Galim", "Bangourain", "Massangam", "Ndé", "Tonga", "Njinikom", "Ndu", "Nkum", "Oku", "Elak",
    "Kom", "Boyo", "Fundong", "Njinikom", "Wum", "Misaje", "Nkambe", "Ako", "Mbven", "Nwa",
    "Batibo", "Widikum", "Pinyin", "Wabane", "Alou", "Fontem", "Nguti", "Toko", "Kupe Muanenguba", "Tombel",
    "Bang", "Bangem", "Melong", "Nlonako", "Mombo", "Loum", "Manjo", "Dibang", "Kekem", "Fongo-Ndeng",
    "Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener",
    "London", "Victoria", "Halifax", "Oshawa", "Windsor", "Saskatoon", "St. Catharines", "Regina", "Sherbrooke", "Kelowna",
    "Abbotsford", "Barrie", "Guelph", "Kingston", "Kanata", "Trois-Rivières", "Cambridge", "Whitby", "Coquitlam", "Burlington",
    "Burnaby", "Richmond", "Markham", "Vaughan", "Mississauga", "Laval", "Brampton", "Surrey", "Longueuil", "Gatineau",
    "North Vancouver", "Saanich", "Delta", "St. John's", "Thunder Bay", "Sudbury", "Peterborough", "Red Deer", "Lethbridge", "Kamloops",
    "Brantford", "Moncton", "Saint John", "Prince George", "Medicine Hat", "Fredericton", "Chilliwack", "Nanaimo", "Belleville", "Sarnia",
    "Fort McMurray", "Welland", "Cornwall", "Chatham", "Georgetown", "Cape Breton", "Granby", "St. Thomas", "Orangeville", "North Bay",
    "Sault Ste. Marie", "Charlottetown", "Brandon", "Joliette", "Shawinigan", "Drummondville", "Rimouski", "Saint-Jérôme", "Chicoutimi", "Victoriaville",
    "Timmins", "Saint-Jean-sur-Richelieu", "Sorel-Tracy", "Levis", "Repentigny", "Mirabel", "Brossard", "Terrebonne", "Saint-Laurent", "LaSalle",
    "Blainville", "Dollard-des-Ormeaux", "Pointe-Claire", "Saint-Léonard", "Anjou", "Verdun", "Pierrefonds-Roxboro", "Saint-Hubert", "Châteauguay", "Mascouche",
    "Bangui", "Bimbo", "Mbaïki", "Berbérati", "Carnot", "Bambari", "Bouar", "Bossangoa", "Bria", "Bangassou",
    "Nola", "Kaga-Bandoro", "Sibut", "Moundou", "Boali", "Damara", "Bozoum", "Batangafo", "Markounda", "Paoua",
    "Boda", "Gambo", "Zemio", "Obo", "Rafaï", "Mobaye", "Alindao", "Kembé", "Ippy", "Grimari",
    "Kouango", "Bakouma", "Sam Ouandja", "Ouadda", "Birao", "Ndélé", "Biltine", "Am-Timan", "Mongo", "Ati",
    "Massenya", "Bongor", "Kélo", "Pala", "Léré", "Fianga", "Laï", "Koyom", "Bousso", "Moïssala",
    "Sarh", "Koumra", "Doba", "Moundou", "Béré", "Gounou-Gaya", "Kyabé", "Moïssala", "Bousso", "Laï",
    "Fianga", "Pala", "Léré", "Kélo", "Bongor", "Massenya", "Ati", "Mongo", "Am-Timan", "Biltine",
    "Ndélé", "Birao", "Ouadda", "Sam Ouandja", "Bakouma", "Kouango", "Grimari", "Ippy", "Kembé", "Alindao",
    "Mobaye", "Rafaï", "Obo", "Zemio", "Gambo", "Boda", "Paoua", "Markounda", "Batangafo", "Bozoum",
    "Boali", "Damara", "Sibut", "Kaga-Bandoro", "Nola", "Bangassou", "Bria", "Bossangoa", "Bouar", "Bambari",
    "N'Djamena", "Moundou", "Sarh", "Abéché", "Kélo", "Koumra", "Pala", "Am Timan", "Bongor", "Mongo",
    "Doba", "Ati", "Laï", "Fianga", "Massenya", "Bousso", "Moïssala", "Kyabé", "Béré", "Gounou-Gaya",
    "Léré", "Biltine", "Oum Hadjer", "Massaguet", "Goz Beida", "Adré", "Iriba", "Bahai", "Farchana", "Guereda",
    "Tissi", "Hadjer Lamis", "Massaguet", "Massakory", "Rig Rig", "Bokoro", "Am Dobak", "Moussoro", "Mao", "Bol",
    "Baga Sola", "Ngouri", "Liwa", "Nokou", "Kiskra", "Mundo", "Barh Signaka", "Melfi", "Dourbali", "Korbol",
    "Lere", "Mayo-Kebbi Ouest", "Bongor", "Fianga", "Gounou-Gaya", "Kanem", "Mao", "Nokou", "Mondo", "Rig Rig",
    "Lac", "Bol", "Mamdi", "Ngouri", "Kaya", "Wayi", "Hadjer-Lamis", "Massakory", "Bokoro", "Am Dobak",
    "Batha", "Oum Hadjer", "Ati", "Yao", "Haraze Mangueigne", "Melfi", "Guéra", "Mongo", "Bitkine", "Mangalmé",
    "Salamat", "Am Timan", "Haraze Al Biar", "Aboudeia", "Moyen-Chari", "Sarh", "Kyabé", "Moïssala", "Mandoul", "Koumra",
    "Béré", "Doba", "Bébédjia", "Béboto", "Miandoum", "Mbikou", "Beinamar", "Bedjondo", "Bégon", "Donia",
    "Santiago", "Valparaíso", "Viña del Mar", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Iquique",
    "Chillán", "Puerto Montt", "Los Ángeles", "Calama", "Copiapó", "Osorno", "Quillota", "Valdivia", "Punta Arenas", "San Antonio",
    "Melipilla", "Curicó", "Ovalle", "Linares", "Tarapacá", "Arica", "Coquimbo", "Quilpué", "Villa Alemana", "San Felipe",
    "Limache", "Casablanca", "Los Andes", "Rengo", "Graneros", "Machalí", "Doñihue", "Olivar", "Coinco", "Coltauco",
    "Quinta de Tilcoco", "Las Cabras", "Peumo", "Pichidegua", "Requínoa", "San Vicente", "Talca", "Constitución", "Curepto", "Empedrado",
    "Maule", "Pelarco", "Pencahue", "Río Claro", "San Clemente", "San Rafael", "Villa Alegre", "Yerbas Buenas", "Colbún", "Linares",
    "Longaví", "Parral", "Retiro", "San Javier", "Cauquenes", "Chanco", "Pelluhue", "Curicó", "Hualañé", "Licantén",
    "Molina", "Rauco", "Romeral", "Sagrada Familia", "Teno", "Vichuquén", "Bulnes", "Chillán", "Chillán Viejo", "Cobquecura",
    "Coelemu", "Coihueco", "El Carmen", "Ninhue", "Ñiquén", "Pemuco", "Pinto", "Portezuelo", "Quillón", "Quirihue",
    "Ránquil", "San Carlos", "San Fabián", "San Ignacio", "San Nicolás", "Treguaco", "Yungay", "Ñuble", "Arauco", "Cañete",
    "Beijing", "Shanghai", "Tianjin", "Chongqing", "Guangzhou", "Shenzhen", "Wuhan", "Dongguan", "Chengdu", "Nanjing",
    "Foshan", "Shenyang", "Hangzhou", "Xi'an", "Harbin", "Qingdao", "Dalian", "Zhengzhou", "Shantou", "Jinan",
    "Changchun", "Kunming", "Changsha", "Taiyuan", "Xiamen", "Hefei", "Shijiazhuang", "Urumqi", "Zibo", "Nanning",
    "Wenzhou", "Ningbo", "Guiyang", "Lanzhou", "Xuzhou", "Weifang", "Anshan", "Fushun", "Yantai", "Zaozhuang",
    "Luoyang", "Datong", "Tangshan", "Baotou", "Benxi", "Yangzhou", "Liuzhou", "Baoding", "Qinhuangdao", "Yichang",
    "Zhenjiang", "Huizhou", "Jining", "Wuxi", "Zhuhai", "Linyi", "Handan", "Jieyang", "Anyang", "Liaocheng",
    "Kaifeng", "Dezhou", "Tai'an", "Jiaxing", "Yinchuan", "Wuhu", "Hengyang", "Shaoxing", "Lianyungang", "Cangzhou",
    "Jilin", "Mudanjiang", "Jiaozuo", "Zhoukou", "Xinxiang", "Rizhao", "Weifang", "Huzhou", "Zhangjiakou", "Langfang",
    "Bengbu", "Jinhua", "Zhenjiang", "Taizhou", "Huai'an", "Yancheng", "Suqian", "Lishui", "Quzhou", "Zhoushan",
    "Taizhou", "Wenzhou", "Jinhua", "Huzhou", "Shaoxing", "Ningbo", "Jiaxing", "Hangzhou", "Qingyuan", "Zhaoqing",
    "Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira", "Santa Marta", "Ibagué",
    "Soledad", "Soacha", "Pasto", "Villavicencio", "Bello", "Valledupar", "Montería", "Itagüí", "Palmira", "Buenaventura",
    "Floridablanca", "Sincelejo", "Popayán", "Barrancabermeja", "Dosquebradas", "Tuluá", "Envigado", "Cartago", "Girardot", "Buga",
    "Tunja", "Florencia", "Maicao", "Sogamoso", "Facatativá", "Armenia", "Riohacha", "Duitama", "Girón", "Magangué",
    "Neiva", "Manizales", "Apartadó", "Zipaquirá", "Turbo", "Quibdó", "Piedecuesta", "Yopal", "Chía", "Fusagasugá",
    "Mosquera", "Madrid", "Funza", "Cajicá", "La Calera", "Tocancipá", "Sopó", "Tenjo", "Tabio", "Cota",
    "Subachoque", "El Rosal", "Bojacá", "Zipacón", "Facatativá", "Sasaima", "Supatá", "La Vega", "San Francisco", "Villeta",
    "Guaduas", "Puerto Salgar", "Honda", "Mariquita", "Armero", "Lérida", "Líbano", "Herveo", "Murillo", "Santa Isabel",
    "Casabianca", "Villahermosa", "Palocabildo", "Ambalema", "Falan", "Fresno", "Palocabildo", "Venadillo", "San Luis", "Roncesvalles",
    "Rovira", "Saldaña", "Purificación", "Guamo", "Espinal", "Coello", "Flandes", "Icononzo", "Melgar", "Carmen de Apicalá",
    "Moroni", "Mutsamudu", "Fomboni", "Domoni", "Sima", "Ouani", "Mramani", "Bambao", "Mitsamiouli", "Mbeni",
    "Foumbouni", "Itsandra", "Ntsoudjini", "Salimani", "Tsidjé", "Chindini", "Singani", "Vanamboini", "Dzaoudzi", "Mamoudzou",
    "Dembéni", "Bandrélé", "Pamandzi", "Labattoir", "Koungou", "M'Tsangamouji", "Acoua", "Bandraboua", "Boueni", "Chirongui",
    "Kani-Kéli", "Ouangani", "Sada", "Tsingoni", "Mtsamboro", "Chiconi", "Combani", "Passamainty", "Trévani", "Kahani",
    "Mtsangadoua", "Dzoumogné", "Iloni", "Mbouini", "Mtsangamouji", "Mtsamboro", "Acoua", "Bandraboua", "Boueni", "Chirongui",
    "Kani-Kéli", "Ouangani", "Sada", "Tsingoni", "Chiconi", "Combani", "Passamainty", "Trévani", "Kahani", "Mtsangadoua",
    "Dzoumogné", "Iloni", "Mbouini", "Koungou", "M'Tsangamouji", "Dembéni", "Bandrélé", "Pamandzi", "Labattoir", "Dzaoudzi",
    "Mamoudzou", "Vanamboini", "Singani", "Chindini", "Tsidjé", "Salimani", "Ntsoudjini", "Itsandra", "Foumbouni", "Mbeni",
    "Mitsamiouli", "Bambao", "Mramani", "Ouani", "Sima", "Domoni", "Fomboni", "Mutsamudu", "Moroni", "Iconi",
    "Nioumachoua", "Bangoi-Mafousa", "Dembéni", "M'Beni", "Washili", "Nyoumakélé", "Tsembehou", "Vouani", "Jomani", "Adda-Douéni",
    "Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Mossendjo", "Ouesso", "Madingou", "Owando", "Sibiti", "Gamboma",
    "Impfondo", "Kinkala", "Makoua", "Djambala", "Ewo", "Boundji", "Loutété", "Divénié", "Zanaga", "Mayoko",
    "Pokola", "Sembé", "Souanké", "Dongou", "Bétou", "Mokéko", "Liouesso", "Bomassa", "Kabo", "Ngbala",
    "Enyellé", "Epéna", "Liranga", "Impfondo", "Dongou", "Bétou", "Mokéko", "Liouesso", "Bomassa", "Kabo",
    "Ngbala", "Enyellé", "Epéna", "Liranga", "Makoua", "Boundji", "Loutété", "Divénié", "Zanaga", "Mayoko",
    "Pokola", "Sembé", "Souanké", "Owando", "Gamboma", "Djambala", "Ewo", "Kinkala", "Mossendjo", "Sibiti",
    "Madingou", "Nkayi", "Dolisie", "Kimongo", "Kakamoeka", "Boko-Songho", "Vindza", "Mouyondzi", "Kimba", "Mfouati",
    "Mindouli", "Kindamba", "Ngabé", "Mayama", "Ngo", "Yamba", "Kellé", "Tchiamba-Nzassi", "Ngoko", "Makoua",
    "Fort-Rousset", "Abala", "Okokila", "Mokéko", "Ngombe", "Pikounda", "Dongou", "Impfondo", "Epéna", "Liranga",
    "Enyellé", "Mokéko", "Liouesso", "Kabo", "Pokola", "Sembé", "Souanké", "Ouesso", "Ngbala", "Bomassa",
    "Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani", "Masina", "Kananga", "Likasi", "Kolwezi", "Tshikapa", "Beni",
    "Bukavu", "Mwene-Ditu", "Kikwit", "Mbandaka", "Matadi", "Uvira", "Butembo", "Gandajika", "Kalemie", "Goma",
    "Kindu", "Isiro", "Bandundu", "Gemena", "Ilebo", "Bunia", "Bumba", "Lisala", "Lodja", "Kenge",
    "Kongolo", "Pweto", "Manono", "Kamina", "Kabinda", "Mweka", "Boende", "Tshela", "Zongo", "Libenge",
    "Gbadolite", "Businga", "Bondo", "Yakoma", "Bumba", "Lisala", "Bosobolo", "Kungu", "Gemena", "Karawa",
    "Dongo", "Libenge", "Zongo", "Imese", "Bokungu", "Djolu", "Inongo", "Oshwe", "Dekese", "Lomela",
    "Tshumbe", "Kole", "Lomami", "Lubao", "Lubefu", "Lusambo", "Miabi", "Tshilenge", "Dibaya", "Demba",
    "Kamonia", "Kasongo Lunda", "Kapanga", "Sandoa", "Dilolo", "Kahemba", "Feshi", "Kasongo", "Kabalo", "Nyunzu",
    "Ankoro", "Kaniama", "Mitwaba", "Upemba", "Malemba-Nkulu", "Bukama", "Kambove", "Kasenga", "Kilwa", "Pweto",
    "Sakania", "Kipushi", "Kasumbalesa", "Mokambo", "Luishia", "Fungurume", "Tenke", "Dilala", "Mutshatsha", "Kawama",
    "San José", "Cartago", "Puntarenas", "Alajuela", "Heredia", "Limón", "Liberia", "Pococí", "San Carlos", "Desamparados",
    "Escazú", "Santa Ana", "Alajuelita", "Vázquez de Coronado", "Acosta", "Tibás", "Moravia", "Montes de Oca", "Turrubares", "Dota",
    "Curridabat", "Pérez Zeledón", "León Cortés Castro", "Oreamuno", "Paraíso", "La Unión", "Jiménez", "Turrialba", "Alvarado", "El Guarco",
    "Grecia", "San Mateo", "Atenas", "Naranjo", "Palmares", "Poás", "Orotina", "San Ramón", "Zarcero", "Sarchí",
    "Valverde Vega", "Upala", "Los Chiles", "Guatuso", "Sarapiquí", "Flores", "San Rafael", "San Isidro", "Belén", "San Pablo",
    "Santo Domingo", "Santa Bárbara", "San Rafael", "San Isidro", "Belén", "Flores", "San Pablo", "Sarapiquí", "Barva", "Santo Domingo",
    "Santa Bárbara", "San Rafael", "San Isidro", "Belén", "Flores", "San Pablo", "Puntarenas", "Esparza", "Buenos Aires", "Montes de Oro",
    "Osa", "Quepos", "Golfito", "Coto Brus", "Parrita", "Corredores", "Garabito", "Aguirre", "Siquirres", "Talamanca",
    "Matina", "Guácimo", "Pococí", "Limón", "Bagaces", "Carrillo", "Cañas", "Abangares", "Tilarán", "Nandayure",
    "La Cruz", "Hojancha", "Nicoya", "Santa Cruz", "Bagaces", "Carrillo", "Cañas", "Abangares", "Tilarán", "Nandayure",
    "Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod", "Pula", "Sesvete", "Karlovac", "Varaždin",
    "Šibenik", "Sisak", "Vinkovci", "Dubrovnik", "Bjelovar", "Koprivnica", "Požega", "Zaprešić", "Solin", "Petrinja",
    "Čakovec", "Samobor", "Vukovar", "Velika Gorica", "Kaštela", "Križevci", "Umag", "Rovinj", "Pazin", "Labin",
    "Poreč", "Opatija", "Crikvenica", "Mali Lošinj", "Rab", "Krk", "Senj", "Gospić", "Otočac", "Novalja",
    "Makarska", "Omiš", "Imotski", "Sinj", "Trilj", "Vrgorac", "Ploče", "Opuzen", "Metković", "Korčula",
    "Vela Luka", "Lastovo", "Mljet", "Cavtat", "Trogir", "Hvar", "Vis", "Brač", "Bol", "Supetar",
    "Postira", "Pučišća", "Selca", "Sutivan", "Milna", "Nerežišća", "Stari Grad", "Jelsa", "Sućuraj", "Vrboska",
    "Komiža", "Krapina", "Pregrada", "Zlatar", "Oroslavje", "Zabok", "Donja Stubica", "Marija Bistrica", "Klanjec", "Kumrovec",
    "Ludbreg", "Đurđevac", "Ferdinandovac", "Molve", "Pitomača", "Podravske Sesvete", "Virje", "Gola", "Legrad", "Kotoriba",
    "Mursko Središće", "Prelog", "Donji Kraljevec", "Donja Dubrava", "Donji Vidovec", "Goričan", "Mala Subotica", "Nedelišće", "Pribislavec", "Savski Marof",
    "Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Guantánamo", "Santa Clara", "Las Tunas", "Bayamo", "Cienfuegos", "Pinar del Río",
    "Matanzas", "Ciego de Ávila", "Sancti Spíritus", "Manzanillo", "Cardenas", "Palma Soriano", "Sagua la Grande", "Artemisa", "Moa", "Baracoa",
    "Florida", "Placetas", "Morón", "Contramaestre", "San José de las Lajas", "Güines", "Trinidad", "Nueva Gerona", "Jovellanos", "Colón",
    "San Antonio de los Baños", "Remedios", "Caibarién", "Esperanza", "Ranchuelo", "Manicaragua", "Camajuaní", "Encrucijada", "Corralillo", "Quemado de Güines",
    "Santo Domingo", "Calabazar de Sagua", "Cifuentes", "Rodas", "Aguada de Pasajeros", "Lajas", "Cruces", "Palmira", "Abreus", "Cumanayagua",
    "Jagüey Grande", "Unión de Reyes", "Pedro Betancourt", "Perico", "Alacranes", "Los Arabos", "Martí", "Limonar", "Cárdenas", "Varadero",
    "Calimete", "Guanajay", "Mariel", "Bahía Honda", "Candelaria", "San Cristóbal", "Los Palacios", "Consolación del Sur", "Viñales", "La Palma",
    "Mantua", "Minas de Matahambre", "Puerto Esperanza", "Dimas", "San Luis", "San Juan y Martínez", "Guane", "Sandino", "Madruga", "Nueva Paz",
    "Jaruco", "Santa Cruz del Norte", "Bejucal", "San Nicolás de Bari", "Güira de Melena", "Alquízar", "Melena del Sur", "Batabanó", "Quivicán", "Nueva Paz",
    "Madruga", "Jaruco", "Santa Cruz del Norte", "Bejucal", "San Nicolás de Bari", "Güira de Melena", "Alquízar", "Melena del Sur", "Batabanó", "Quivicán",
    "Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta", "Kyrenia", "Protaras", "Ayia Napa", "Paralimni", "Polis",
    "Morphou", "Lefkara", "Omodos", "Platres", "Pedoulas", "Kakopetria", "Galata", "Kalopanayiotis", "Moutoullas", "Prodromos",
    "Pano Platres", "Kato Platres", "Agros", "Spilia", "Pelendri", "Potamitissa", "Trimiklini", "Zoopigi", "Doros", "Apsiou",
    "Laneia", "Vouni", "Koilani", "Arsos", "Vasa", "Kilani", "Pachna", "Prastio", "Mandria", "Kelokedara",
    "Souni", "Zanakia", "Finikaria", "Louvaras", "Alassa", "Erimi", "Kolossi", "Episkopi", "Paramali", "Avdimou",
    "Pissouri", "Kouklia", "Mandria", "Timi", "Chlorakas", "Empa", "Konia", "Mesogi", "Koloni", "Anarita",
    "Stroumbi", "Polemi", "Tsada", "Koili", "Kathikas", "Pegeia", "Droushia", "Ineia", "Akoursos", "Neo Chorio",
    "Latchi", "Pomos", "Pachyammos", "Kato Pyrgos", "Morfou", "Lefka", "Karavostasi", "Vokolida", "Petra", "Limnitis",
    "Kokkina", "Mansoura", "Pyrgos", "Tylliria", "Kambos", "Evrychou", "Flasou", "Temvria", "Oikos", "Asinou",
    "Nikitari", "Kyperounta", "Chandria", "Polystypos", "Amiantos", "Palaichori", "Farmakas", "Lazanias", "Gourri", "Alona",
    "Prague", "Brno", "Ostrava", "Plzen", "Liberec", "Olomouc", "Ceske Budejovice", "Hradec Kralove", "Usti nad Labem", "Pardubice",
    "Havirov", "Zlin", "Most", "Opava", "Frydek-Mistek", "Karviná", "Jihlava", "Teplice", "Decin", "Karlovy Vary",
    "Jablonec nad Nisou", "Mlada Boleslav", "Prostejov", "Prerov", "Ceska Lipa", "Tabor", "Trinec", "Znojmo", "Pribram", "Cheb",
    "Trutnov", "Orlova", "Chomutov", "Kolin", "Pisek", "Kromeriz", "Sumperk", "Vsetin", "Novy Jicin", "Litomerice",
    "Valasske Mezirici", "Uherske Hradiste", "Bruntal", "Jicin", "Blansko", "Karvina", "Hodonin", "Strakonice", "Beroun", "Varnsdorf",
    "Kladno", "Kutna Hora", "Nachod", "Jindrichuv Hradec", "Sokolov", "Litvinov", "Rumburk", "Koprivnice", "Pelhrimov", "Nymburk",
    "Nove Mesto na Morave", "Cesky Tesin", "Rosice", "Otrokovice", "Rychnov nad Kneznou", "Lipnik nad Becvou", "Unicov", "Bruntál", "Sternberk", "Moravsky Beroun",
    "Jesenik", "Zamberk", "Lomnice nad Popelkou", "Tachov", "Marianske Lazne", "Ostrov", "Kralupy nad Vltavou", "Neratovice", "Melnik", "Roudnice nad Labem",
    "Lovosice", "Bilina", "Duchcov", "Kadan", "Zatec", "Louny", "Rakovnik", "Slany", "Klasterec nad Ohri", "Jirkov",
    "Litvínov", "Rumburk", "Varnsdorf", "Decin", "Usti nad Labem", "Teplice", "Most", "Chomutov", "Karlovy Vary", "Sokolov",

    // D
    "Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde",
    "Herning", "Helsingør", "Silkeborg", "Næstved", "Fredericia", "Viborg", "Køge", "Holstebro", "Taastrup", "Slagelse",
    "Hillerød", "Sønderborg", "Svendborg", "Hjørring", "Frederikshavn", "Haderslev", "Nørresundby", "Ringsted", "Ølgod", "Korsør",
    "Skive", "Nyborg", "Vordingborg", "Kalundborg", "Thisted", "Faaborg", "Bramming", "Ikast", "Bogense", "Rudkøbing",
    "Nykøbing F", "Middelfart", "Nakskov", "Tønder", "Grenaa", "Rønne", "Kerteminde", "Lemvig", "Struer", "Løgstør",
    "Hobro", "Hirtshals", "Blokhus", "Løkken", "Skagen", "Nibe", "Støvring", "Brovst", "Pandrup", "Aabybro",
    "Fjerritslev", "Brønderslev", "Dronninglund", "Sindal", "Sæby", "Frederikshavn", "Skagen", "Hirtshals", "Hjørring", "Vraa",
    "Bindslev", "Tornby", "Lønstrup", "Rubjerg", "Tversted", "Kandestederne", "Blokhus", "Løkken", "Thorupstrand", "Agger",
    "Thyborøn", "Harboøre", "Lemvig", "Ringkøbing", "Hvide Sande", "Søndervig", "Bjerregård", "Vejers", "Blåvand", "Fanø",
    "Esbjerg", "Bramming", "Ribe", "Skærbæk", "Tønder", "Højer", "Rømø", "Løgumkloster", "Aabenraa", "Gråsten",
    "Djibouti City", "Ali Sabieh", "Dikhil", "Tadjourah", "Obock", "Arta", "Holhol", "Yoboki", "Gobaad", "As Eyla",
    "Randa", "Day Forest", "Galafi", "Loyada", "Doraleh", "Nagad", "Khor Angar", "Sagallou", "Balho", "Airolaf",
    "Chebelley", "Guelile", "Holl-Holl", "Moulhoule", "Goubetto", "Assamo", "Dikhil", "Ali Adde", "Gombourta", "Weah",
    "As Ela", "Arta", "Holhol", "Loyada", "Doraleh", "Nagad", "Khor Angar", "Sagallou", "Balho", "Airolaf",
    "Chebelley", "Guelile", "Holl-Holl", "Moulhoule", "Goubetto", "Assamo", "Dikhil", "Ali Adde", "Gombourta", "Weah",
    "As Ela", "Tadjourah", "Obock", "Khor Angar", "Sagallou", "Balho", "Airolaf", "Chebelley", "Guelile", "Holl-Holl",
    "Moulhoule", "Goubetto", "Assamo", "Dikhil", "Ali Adde", "Gombourta", "Weah", "As Ela", "Randa", "Day Forest",
    "Galafi", "Loyada", "Doraleh", "Nagad", "Khor Angar", "Sagallou", "Balho", "Airolaf", "Chebelley", "Guelile",
    "Holl-Holl", "Moulhoule", "Goubetto", "Assamo", "Dikhil", "Ali Adde", "Gombourta", "Weah", "As Ela", "Tadjourah",
    "Obock", "Khor Angar", "Sagallou", "Balho", "Airolaf", "Chebelley", "Guelile", "Holl-Holl", "Moulhoule", "Goubetto",
    "Roseau", "Portsmouth", "Marigot", "Atkinson", "Mahaut", "Canefield", "Saint Joseph", "Layou", "Massacre", "Salisbury",
    "Soufrière", "Scotts Head", "Pointe Michel", "Grand Bay", "Berekua", "Delices", "Petite Savanne", "Boetica", "Castle Bruce", "Good Hope",
    "Hatton Garden", "Marigot", "Wesley", "Woodford Hill", "Calibishie", "Melville Hall", "Penville", "Hampstead", "Portsmouth", "Lagoon",
    "Tanetane", "Toucari", "Capuchin", "Clifton", "Prince Rupert Bay", "Indian River", "Glanvillia", "Lagoon", "Tanetane", "Toucari",
    "Capuchin", "Clifton", "Cottage", "Savanne Paille", "Colihaut", "Dublanc", "Bioche", "Coulibistrie", "Bataka", "Morne Raquette",
    "Saint Joseph", "Layou", "Massacre", "Mahaut", "Canefield", "Fond Cani", "Jimmit", "Goodwill", "Boeri Lake", "Freshwater Lake",
    "Trafalgar Falls", "Middleham Falls", "Victoria Falls", "Emerald Pool", "Titou Gorge", "Champagne Reef", "Scotts Head", "Soufrière",
    "Galion", "Grand Fond", "Petite Savanne", "Delices", "Boetica", "Good Hope", "Castle Bruce", "Hatton Garden", "Belle Fille", "Londonderry",
    "Bellevue Chopin", "Sineku", "Carib Territory", "Salybia", "Bataca", "Atkinson", "Giraudel", "Eggleston", "Wotten Waven", "Trafalgar",
    "Laudat", "Pont Cassé", "Bells", "Morne Prosper", "Morne Daniel", "Fond Cole", "Riverside", "Bath Estate", "Newtown", "Pottersville",
    "Santo Domingo", "Santiago de los Caballeros", "Los Alcarrizos", "La Romana", "San Pedro de Macorís", "San Francisco de Macorís", "Puerto Plata", "San Cristóbal", "Concepción de La Vega", "Higüey",
    "Baní", "Bonao", "Cotuí", "Moca", "Azua de Compostela", "Bajos de Haina", "Mao", "Monte Cristi", "Esperanza", "Jarabacoa",
    "Villa Altagracia", "Nagua", "Dajabón", "Constanza", "San José de Ocoa", "Villa Bisonó", "Salcedo", "Tamboril", "Samaná", "Barahona",
    "San Juan de la Maguana", "Hato del Yaque", "Valverde", "Villa Tapia", "Las Matas de Farfán", "Sabana Grande de Boyá", "Sabana de la Mar", "Montecristi", "Luperón", "Río San Juan",
    "Cabrera", "Villa Vásquez", "Villa González", "Gaspar Hernández", "Villa Trina", "Monción", "Guayubín", "Laguna Salada", "Esperanza", "Villa Riva",
    "Villa Rivas", "Fantino", "Tenares", "Cayetano Germosén", "Castillo", "Eugenio María de Hostos", "Sabana Iglesia", "Jánico", "San José de las Matas", "Imbert",
    "Altamira", "Loma de Cabrera", "Restauración", "Santiago Rodríguez", "Villa Los Almácigos", "Sabaneta", "Montecristi", "Pepillo Salcedo", "Guayubín", "Villa Vásquez",
    "Castañuelas", "Las Matas de Santa Cruz", "Villa Tapia", "Cevicos", "Fantino", "Villa Rivas", "Pimentel", "Villa Trina", "Cayetano Germosén", "Castillo",
    "Río San Juan", "Cabrera", "Nagua", "El Factor", "Las Terrenas", "Sánchez", "Las Galeras", "Santa Bárbara de Samaná", "Samaná", "El Limón",
    "Villa Montellano", "Sabana de la Mar", "Miches", "El Seibo", "Hato Mayor del Rey", "Yerba Buena", "El Valle", "Sabana de la Mar", "Ramón Santana", "Guaymate",

    // E
    "Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala", "Durán", "Manta", "Portoviejo", "Ambato", "Riobamba",
    "Loja", "Esmeraldas", "Ibarra", "Milagro", "Quevedo", "La Libertad", "Babahoyo", "Tulcán", "Pasaje", "Salinas",
    "Daule", "El Carmen", "Otavalo", "Chone", "Sangolquí", "Latacunga", "Guaranda", "Azogues", "Macas", "Nueva Loja",
    "Tena", "Puyo", "Zamora", "Yantzaza", "Gualaceo", "Playas", "Pedro Carbo", "Naranjal", "El Triunfo", "Balzar",
    "Velasco Ibarra", "Nobol", "Samborondón", "Yaguachi", "Santa Elena", "Ancón", "Atuntaqui", "Cotacachi", "Cayambe",
    "Pedro Moncayo", "Tabacundo", "El Chaco", "Archidona", "Carlos Julio Arosemena Tola", "Arajuno", "Santa Clara", "Pastaza", "Mera", "Shell",
    "Palora", "Huamboya", "Sucúa", "Logroño", "Santiago de Méndez", "Limón Indanza", "San Juan Bosco", "Gualaquiza", "El Pangui", "Centinela del Cóndor",
    "Palanda", "Chinchipe", "El Chaco", "Gonzalo Pizarro", "Putumayo", "Shushufindi", "Cuyabeno", "Cascales", "Cononaco", "Loreto",
    "Aguarico", "La Joya de los Sachas", "Francisco de Orellana", "Arosemena Tola", "Santa Clara", "Mera", "Shell", "Puyo", "Pastaza", "Palora",
    "Huamboya", "Morona", "Sucúa", "Logroño", "Pablo Sexto", "Santiago de Méndez", "Limón Indanza", "San Juan Bosco", "Gualaquiza", "El Pangui",
    "Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Luxor", "Mansoura", "El Mahalla El Kubra", "Tanta",
    "Asyut", "Ismailia", "Fayyum", "Zagazig", "Aswan", "Damietta", "Damanhur", "Minya", "Beni Suef", "Hurghada",
    "Qena", "Sohag", "Shibin El Kom", "Banha", "Kafr El Sheikh", "Arish", "Mallawi", "Bilbais", "Mit Ghamr", "Al Kharga",
    "Idfu", "Girga", "Akhmim", "Marsa Matruh", "Qalyub", "Abu Kabir", "Kafr El Dawwar", "Desouk", "Samannud", "Dikirnis",
    "Faraskur", "Fuwah", "Rashid", "Baltim", "Ras El Bar", "New Damietta", "Gamasa", "Ezbet El Borg", "Mit Salsil", "Sherbin",
    "Aga", "Minyat El Nasr", "Belqas", "Mit Ghamr", "Daqahliya", "Talkha", "Nabaroh", "Mahallet Damana", "Mahallet Rouh", "Temay El Amdid",
    "Kom Hamada", "Abu Hummus", "Hosh Isa", "Itay El Barud", "Rahmaniya", "Shubrakheet", "El Delengat", "Wadi El Natrun", "Abu El Matamir", "Edko",
    "Rosetta", "Kafr El Dawwar", "Damanhur", "Housh Eissa", "Kom Hamada", "Abu Hummus", "Itay El Barud", "Rahmaniya", "Shubrakheet", "El Delengat",
    "Wadi El Natrun", "Abu El Matamir", "Edko", "Rosetta", "Kafr El Dawwar", "Damanhur", "Housh Eissa", "Kom Hamada", "Abu Hummus", "Itay El Barud",
    "Rahmaniya", "Shubrakheet", "El Delengat", "Wadi El Natrun", "Abu El Matamir", "Edko", "Rosetta", "Baltim", "Ras El Bar", "New Damietta",
    "San Salvador", "Soyapango", "Santa Ana", "San Miguel", "Mejicanos", "Santa Tecla", "Apopa", "Delgado", "Sonsonate", "Ahuachapán",
    "Ilopango", "Chalatenango", "Cojutepeque", "Usulután", "Zacatecoluca", "La Unión", "Sensuntepeque", "San Vicente", "Antiguo Cuscatlán", "Ayutuxtepeque",
    "Tonacatepeque", "Quezaltepeque", "Nejapa", "Aguilares", "El Paisnal", "Guazapa", "Cuscatancingo", "San Martín", "Santiago Texacuangos", "Rosario de Mora",
    "Santo Tomás", "San Marcos", "Panchimalco", "Ilopango", "Soyapango", "Delgado", "Mejicanos", "Ayutuxtepeque", "Cuscatancingo", "Ciudad Delgado",
    "Apopa", "Nejapa", "Quezaltepeque", "San Salvador", "Antiguo Cuscatlán", "Santa Tecla", "Huizúcar", "Tamanique", "Chiltiupán", "Jicalapa",
    "La Libertad", "Puerto de La Libertad", "Santa Tecla", "Antiguo Cuscatlán", "Huizúcar", "Tamanique", "Chiltiupán", "Jicalapa", "Teotepeque", "Talnique",
    "Comasagua", "Jayaque", "Sacacoyo", "Tepecoyo", "Ciudad Arce", "Colón", "San Juan Opico", "Zaragoza", "Armenia", "Sonzacate",
    "Nahuizalco", "Izalco", "Caluco", "Santo Domingo de Guzmán", "San Julián", "Cuisnahuat", "Santa Isabel Ishuatán", "Acajutla", "Sonsonate", "Juayúa",
    "Salcoatitán", "Santa Catarina Masahuat", "San Antonio del Monte", "Nahulingo", "San Pedro Puxtla", "Ahuachapán", "Jujutla", "Atiquizaya", "El Refugio", "San Lorenzo",
    "Turín", "San Francisco Menéndez", "Guaymango", "Apaneca", "Concepción de Ataco", "Tacuba", "San Pedro Puxtla", "Atiquizaya", "El Refugio", "San Lorenzo",
    "Malabo", "Bata", "Ebebiyin", "Aconibe", "Añisok", "Luba", "Evinayong", "Mongomo", "Mengomeyén", "Mikomeseng",
    "Niefang", "Nsok", "Ayene", "Bicurga", "Cogo", "Kogo", "Acurenam", "Mbini", "Rio Campo", "Corisco",
    "San Antonio de Palé", "Annobon", "Rebola", "Sampaka", "Baney", "Moka", "Ureka", "Riaba", "San Carlos", "Ela Nguema",
    "Nsang", "Akurenam", "Machinda", "Ebibeyin", "Ncue", "Añisok", "Aconibe", "Nsok", "Niefang", "Ayene",
    "Bicurga", "Cogo", "Kogo", "Acurenam", "Mbini", "Rio Campo", "Corisco", "San Antonio de Palé", "Annobon", "Rebola",
    "Sampaka", "Baney", "Moka", "Ureka", "Riaba", "San Carlos", "Ela Nguema", "Nsang", "Akurenam", "Machinda",
    "Ebibeyin", "Ncue", "Añisok", "Aconibe", "Nsok", "Niefang", "Ayene", "Bicurga", "Cogo", "Kogo",
    "Acurenam", "Mbini", "Rio Campo", "Corisco", "San Antonio de Palé", "Annobon", "Rebola", "Sampaka", "Baney", "Moka",
    "Ureka", "Riaba", "San Carlos", "Ela Nguema", "Nsang", "Akurenam", "Machinda", "Ebibeyin", "Ncue", "Añisok",
    "Aconibe", "Nsok", "Niefang", "Ayene", "Bicurga", "Cogo", "Kogo", "Acurenam", "Mbini", "Rio Campo",
    "Asmara", "Assab", "Massawa", "Keren", "Mendefera", "Barentu", "Adi Keih", "Adi Quala", "Dekemhare", "Akurdet",
    "Teseney", "Ghinda", "Nefasit", "Adi Ugri", "Mai-Mne", "Senafe", "Tsorona", "Zalambessa", "Molqe", "Rama",
    "Halhal", "Segeneiti", "Debarwa", "Areza", "Hazega", "Adi Tekelezan", "Mai-Aini", "Dubarwa", "Adi Keih", "Senafe",
    "Tsorona", "Zalambessa", "Rama", "Molqe", "Halhal", "Segeneiti", "Debarwa", "Areza", "Hazega", "Adi Tekelezan",
    "Mai-Aini", "Dubarwa", "Adi Keih", "Senafe", "Tsorona", "Zalambessa", "Rama", "Molqe", "Halhal", "Segeneiti",
    "Debarwa", "Areza", "Hazega", "Adi Tekelezan", "Mai-Aini", "Dubarwa", "Keren", "Halibmentel", "Elabered", "Hagaz",
    "Ad Tekelezan", "Nakfa", "Afabet", "Karora", "Barentu", "Agordat", "Omhajer", "Mensura", "Logo Anseba", "Hamelmalo",
    "Gherset", "Shambuko", "Geleb", "Gogne", "Kerkebet", "Teseney", "Omhajer", "Mensura", "Logo Anseba", "Hamelmalo",
    "Gherset", "Shambuko", "Geleb", "Gogne", "Kerkebet", "Forto", "Sheeb", "Goluj", "Ali Ghedir", "Assab",
    "Ed", "Rahaita", "Afdera", "Beilul", "Massawa", "Ghinda", "Nefasit", "Adi Ugri", "Mai-Mne", "Asmara",
    "Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi", "Rakvere", "Maardu", "Sillamäe", "Kuressaare",
    "Võru", "Valga", "Haapsalu", "Jõhvi", "Paide", "Keila", "Kiviõli", "Tapa", "Põlva", "Elva",
    "Saue", "Loo", "Tõrva", "Kärdla", "Kehra", "Kunda", "Otepää", "Türi", "Karksi-Nuia", "Antsla",
    "Rapla", "Põltsamaa", "Jõgeva", "Mustvee", "Kallaste", "Lihula", "Märjamaa", "Kohila", "Kilingi-Nõmme", "Abja-Paluoja",
    "Suure-Jaani", "Võhma", "Kõpu", "Järvakandi", "Kehtna", "Tori", "Audru", "Lavassaare", "Lindi", "Paikuse",
    "Sauga", "Sindi", "Surju", "Tahkuranna", "Tootsi", "Vändra", "Are", "Häädemeeste", "Kabli", "Kilingi-Nõmme",
    "Saarde", "Tali", "Urissaare", "Varbla", "Hanila", "Karuse", "Koonga", "Kullamaa", "Lihula", "Martna",
    "Nova", "Nõva", "Oru", "Ridala", "Risti", "Taebla", "Tubala", "Vormsi", "Emmaste", "Hiiumaa",
    "Käina", "Kärla", "Kärdla", "Pühalepa", "Reigi", "Mustjala", "Orissaare", "Pihtla", "Pöide", "Salme",
    "Torgu", "Valjala", "Kihelkonna", "Laimjala", "Leisi", "Muhu", "Ruhnu", "Alatskivi", "Peipsiääre", "Kasepää",
    "Mbabane", "Manzini", "Big Bend", "Malkerns", "Nhlangano", "Piggs Peak", "Siteki", "Lobamba", "Hluti", "Simunye",
    "Matsapha", "Ezulwini", "Bhunya", "Lavumisa", "Mahamba", "Mankayane", "Hlatikulu", "Tshaneni", "Bulembu", "Maguga",
    "Sidvokodvo", "Mlawula", "Mananga", "Magwegwe", "Mhlume", "Tabankulu", "Mahlanya", "Ngwenya", "Mahlangatja", "Maloma",
    "Mpolonjeni", "Dalriach", "Vuvulane", "Tambankulu", "Mphepheni", "Lomahasha", "Ngudzeni", "Shiselweni", "Lubuli", "Zombodze",
    "Hlathikhulu", "Nkoyoyo", "Sandleni", "Mgwagwa", "Sigombeni", "Nhletjeni", "Mhlosheni", "Manzini", "Matsapha", "Ezulwini",
    "Bhunya", "Lavumisa", "Mahamba", "Mankayane", "Hlatikulu", "Tshaneni", "Bulembu", "Maguga", "Sidvokodvo", "Mlawula",
    "Mananga", "Magwegwe", "Mhlume", "Tabankulu", "Mahlanya", "Ngwenya", "Mahlangatja", "Maloma", "Mpolonjeni", "Dalriach",
    "Vuvulane", "Tambankulu", "Mphepheni", "Lomahasha", "Ngudzeni", "Shiselweni", "Lubuli", "Zombodze", "Hlathikhulu", "Nkoyoyo",
    "Sandleni", "Mgwagwa", "Sigombeni", "Nhletjeni", "Mhlosheni", "Big Bend", "Malkerns", "Nhlangano", "Piggs Peak", "Siteki",
    "Lobamba", "Hluti", "Simunye", "Matsapha", "Ezulwini", "Bhunya", "Lavumisa", "Mahamba", "Mankayane", "Hlatikulu",
    "Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Awassa", "Bahir Dar", "Dessie", "Jimma", "Jijiga", "Shashamane",
    "Nazret", "Harar", "Debre Zeit", "Nekemte", "Debre Berhan", "Debre Markos", "Kombolcha", "Hosaena", "Arba Minch", "Dilla",
    "Sodo", "Debre Tabor", "Aksum", "Shire", "Adigrat", "Wukro", "Alamata", "Kobo", "Lalibela", "Sekota",
    "Woldiya", "Dessie", "Kombolcha", "Kemise", "Debre Sina", "Shewa Robit", "Debre Berhan", "Ankober", "Efeson", "Gerba Guracha",
    "Sendafa", "Sululta", "Chancho", "Fiche", "Degem", "Gida Ayana", "Shambu", "Fincha", "Nekemte", "Gimbi",
    "Dembi Dollo", "Gambela", "Itang", "Abobo", "Gog", "Dimma", "Metu", "Gore", "Tepi", "Mizan Teferi",
    "Bonga", "Dawro", "Tarcha", "Chena", "Basketo", "Male", "Jinka", "Turmi", "Omorate", "Konso",
    "Yabelo", "Moyale", "Mega", "Hagere Mariam", "Alaba Kulito", "Butajira", "Welkite", "Worabe", "Hosaina", "Durame",
    "Fonko", "Boditi", "Areka", "Wolaita Sodo", "Gesuba", "Shashogo", "Humbo", "Dilla", "Yirgachefe", "Wenago",
    "Bule Hora", "Hagere Selam", "Negele", "Arero", "Teltele", "Yabelo", "Moyale", "Mega", "Miyo", "Dubluk",

    // F
  ]