export const weatherInfo = {
    "-50--15": {
        day: {
            image: "extreme-freeze.png",
            alt: "Extreme freezing cold (Day)",
            note: "Dangerously cold ❄️. Stay indoors if possible!",
        },
        night: {
            image: "extreme-freeze-night.jpg",
            alt: "Extreme freezing cold (Night)",
            note: "Freezing night ❄️. Stay warm and avoid going out!",
        },
    },
    "-15--10": {
        day: {
            image: "very-cold.png",
            alt: "Very cold weather (Day)",
            note: "Very cold! Dress in layers and cover up.",
        },
        night: {
            image: "very-cold-night.jpg",
            alt: "Very cold weather (Night)",
            note: "Very cold night 🌙. Extra blankets recommended.",
        },
    },
    "-10--5": {
        day: {
            image: "cold.png",
            alt: "Cold temperature (Day)",
            note: "Cold weather, wear a warm jacket.",
        },
        night: {
            image: "cold-night.jpg",
            alt: "Cold temperature (Night)",
            note: "Chilly night, wear thick clothes to stay warm.",
        },
    },
    "-5-0": {
        day: {
            image: "chilly.png",
            alt: "Chilly near freezing (Day)",
            note: "Chilly, gloves and hats recommended.",
        },
        night: {
            image: "chilly-night.jpg",
            alt: "Chilly near freezing (Night)",
            note: "Cold night near freezing ❄️. Keep warm indoors.",
        },
    },
    "0-5": {
        day: {
            image: "cool.png",
            alt: "Cool temperature (Day)",
            note: "Cool weather. Light jacket needed.",
        },
        night: {
            image: "cool-night.jpg",
            alt: "Cool temperature (Night)",
            note: "Cool night, keep a blanket handy.",
        },
    },
    "5-10": {
        day: {
            image: "mild-cool.png",
            alt: "Mildly cool (Day)",
            note: "Mildly cool, a sweater should be fine.",
        },
        night: {
            image: "mild-cool-night.jpg",
            alt: "Mildly cool (Night)",
            note: "Slightly cold night, sweater or light blanket recommended.",
        },
    },
    "10-15": {
        day: {
            image: "pleasant.png",
            alt: "Pleasant weather (Day)",
            note: "Pleasant and fresh, great for a walk outside.",
        },
        night: {
            image: "pleasant-night.jpg",
            alt: "Pleasant weather (Night)",
            note: "Comfortable evening, perfect for a night stroll.",
        },
    },
    "15-20": {
        day: {
            image: "warm.png",
            alt: "Warm weather (Day)",
            note: "Mildly cool 🌤️. Feels nice and a bit fresh outside.",
        },
        night: {
            image: "warm-night.jpg",
            alt: "Warm weather (Night)",
            note: "Cool night 🌙. A sweater or blanket may be needed.",
        },
    },
    "20-25": {
        day: {
            image: "comfortably-warm.png",
            alt: "Comfortably warm (Day)",
            note: "Nice and warm, perfect for outdoor activities.",
        },
        night: {
            image: "comfortably-warm-night.jpg",
            alt: "Comfortably warm (Night)",
            note: "Warm night 🌙. A light breeze keeps it nice.",
        },
    },
    "25-30": {
        day: {
            image: "hot.png",
            alt: "Hot temperature (Day)",
            note: "Hot weather 🌞, stay hydrated.",
        },
        night: {
            image: "hot-night.jpg",
            alt: "Hot temperature (Night)",
            note: "Warm night, keep hydrated and cool.",
        },
    },
    "30-35": {
        day: {
            image: "very-hot.png",
            alt: "Very hot weather (Day)",
            note: "Very hot! Avoid being outside too long.",
        },
        night: {
            image: "very-hot-night.jpg",
            alt: "Very hot weather (Night)",
            note: "Hot evening 🌙. Use fans or AC to stay cool.",
        },
    },
    "35-50": {
        day: {
            image: "extreme-heat.png",
            alt: "Extreme heat (Day)",
            note: "Extreme heat 🌋. Stay cool and drink lots of water!",
        },
        night: {
            image: "extreme-heat-night.jpg",
            alt: "Extreme heat (Night)",
            note: "Very hot night 🌙. Avoid heavy activities and stay hydrated.",
        },
    },
};

export const rainInfo = {
    "0-1": {
        day: {
            image: "light-rain.png",
            alt: "Light rain (Day)",
            note: "Drizzle ☔. A light umbrella is enough.",
        },
        night: {
            image: "light-rain-night.jpg",
            alt: "Light rain (Night)",
            note: "Light showers 🌧️. Roads may be a little slippery.",
        },
    },
    "1-5": {
        day: {
            image: "moderate-rain.png",
            alt: "Moderate rain (Day)",
            note: "Moderate rain ☔. Take a proper umbrella or raincoat.",
        },
        night: {
            image: "moderate-rain-night.jpg",
            alt: "Moderate rain (Night)",
            note: "Steady rainfall 🌧️. Drive carefully.",
        },
    },
    "5-20": {
        day: {
            image: "heavy-rain.png",
            alt: "Heavy rain (Day)",
            note: "Heavy rain 🌧️. Stay safe, possible waterlogging.",
        },
        night: {
            image: "heavy-rain-night.jpg",
            alt: "Heavy rain (Night)",
            note: "Strong rainfall 🌧️. Avoid unnecessary travel.",
        },
    },
    "20-100": {
        day: {
            image: "extreme-rain.png",
            alt: "Extreme rain (Day)",
            note: "Extreme rain ⛈️. Flooding possible, stay indoors!",
        },
        night: {
            image: "extreme-rain-night.jpg",
            alt: "Extreme rain (Night)",
            note: "Dangerous rainfall ⛈️. Avoid going outside.",
        },
    },
};

export const cities = [
    // A
    "Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad", "Kunduz", "Lashkar Gah", "Taloqan", "Pul-e Khumri", "Ghazni",
    "Faizabad", "Khost", "Gardez", "Bamyan", "Charikar", "Shiberghan", "Asadabad", "Aibak", "Baghlan", "Mahmud-e Raqi",
    "Mehtarlam", "Qalat", "Zaranj", "Farah", "Chaghcharan", "Nili", "Tarinkot", "Qala-e Naw", "Parun", "Maidan Shahr",
    "Bazarak", "Panjshir", "Sharana", "Spin Boldak", "Gereshk", "Nad Ali", "Sangin", "Musa Qala", "Kajaki", "Marjah",
    "Helmand", "Uruzgan", "Daikundi", "Ghor", "Badghis", "Faryab", "Jawzjan", "Sar-e Pol", "Balkh", "Samangan",
    "Baghlan", "Takhar", "Badakhshan", "Nuristan", "Laghman", "Nangarhar", "Kunar", "Kapisa", "Parwan", "Wardak",
    "Logar", "Ghazni", "Paktika", "Paktia", "Khost", "Zabul", "Kandahar", "Helmand", "Nimroz", "Farah",
    "Herat", "Badghis", "Faryab", "Jawzjan", "Sar-e Pol", "Balkh", "Samangan", "Baghlan", "Kunduz", "Takhar",
    "Badakhshan", "Panjshir", "Kapisa", "Parwan", "Kabul", "Wardak", "Logar", "Ghazni", "Paktika", "Paktia",
    "Khost", "Nangarhar", "Laghman", "Kunar", "Nuristan", "Bamyan", "Daikundi", "Ghor", "Uruzgan", "Zabul",
    "Tirana", "Durrës", "Vlorë", "Shkodër", "Fier", "Korçë", "Elbasan", "Berat", "Lushnjë", "Kavajë",
    "Gjirokastër", "Sarandë", "Laç", "Kukës", "Lezhë", "Pogradec", "Patos", "Krujë", "Kuçovë", "Burrel",
    "Cërrik", "Ballsh", "Mamurras", "Gramsh", "Peqin", "Bilisht", "Himarë", "Divjakë", "Delvinë", "Selenicë",
    "Roskovec", "Libohovë", "Memaliaj", "Bajram Curri", "Bulqizë", "Maliq", "Koplik", "Poliçan", "Përmet",
    "Ersekë", "Kamëz", "Vorë", "Rrogozhinë", "Shijak", "Pukë", "Finiq", "Konispol", "Tepelenë", "Këlcyrë",
    "Dropull", "Libohova", "Leskovik", "Kolonjë", "Devoll", "Malësi e Madhe", "Vau i Dejës", "Mirditë", "Mat", "Dibër",
    "Bulqizë", "Librazhd", "Prrenjas", "Belsh", "Mallakastër", "Lushnje", "Fier", "Divjakë", "Roskovec", "Patos",
    "Ballsh", "Vlorë", "Himarë", "Delvinë", "Sarandë", "Konispol", "Finiq", "Dropull", "Gjirokastër", "Përmet",
    "Këlcyrë", "Tepelenë", "Memaliaj", "Libohova", "Leskovik", "Kolonjë", "Devoll", "Korçë", "Pogradec", "Maliq",
    "Bilisht", "Ersekë", "Librazhd", "Prrenjas", "Gramsh", "Elbasan", "Peqin", "Cërrik", "Belsh", "Berat",
    "Algiers", "Oran", "Constantine", "Batna", "Djelfa", "Sétif", "Annaba", "Sidi Bel Abbès", "Biskra", "Tébessa",
    "Tiaret", "Béjaïa", "Tlemcen", "Ouargla", "Skikda", "Mostaganem", "M'Sila", "Oum El Bouaghi", "Chlef", "Médéa",
    "Tizi Ouzou", "El Oued", "Khenchela", "Souk Ahras", "Mascara", "Relizane", "Saïda", "Laghouat", "Bordj Bou Arréridj", "Bouira",
    "Tamanrasset", "Tissemsilt", "Jijel", "Guelma", "Ain Defla", "Naama", "Ain Témouchent", "Ghardaïa", "El Bayadh", "Illizi",
    "Bordj Badji Mokhtar", "Béni Abbès", "Timimoun", "Ouled Djellal", "In Salah", "In Guezzam", "Touggourt", "Djanet", "El M'Ghair", "El Meniaa",
    "Blida", "Boumerdès", "Tipaza", "Ain Benian", "Zeralda", "El Achir", "Bou Ismail", "Koléa", "Cherchell", "Hadjout",
    "Larbaâ", "Boufarik", "Larbaa", "Meftah", "Ouled Yaïch", "Bougara", "Chiffa", "El Affroun", "Hammam Melouane", "Oued Alleug",
    "Soumaa", "Ben Khellil", "Guerrouaou", "Ouled Slama", "Bir Ghbalou", "Sour El Ghozlane", "Ain Bessem", "Bechloul", "El Hakimia", "Dirah",
    "El Adjiba", "Haizer", "El Esnam", "Ridane", "Bir El Ater", "Ouenza", "El Kouif", "Negrine", "Ferkane", "El Houidjbet",
    "Bekkaria", "Stah Guentis", "El Mezeraa", "Youkous", "Zeribet El Oued", "Kais", "El Mahmal", "Tamlouka", "Ibn Ziad", "Ouled Hamla",
    "Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria", "La Massana", "Santa Coloma d'Andorra", "Ordino", "El Pas de la Casa", "Soldeu", "Canillo",
    "Arinsal", "Pal", "La Cortinada", "Llorts", "El Serrat", "Anyós", "Bixessarri", "Fontaneda", "Nagol", "Aixàs",
    "Juberri", "Certers", "Llumeneres", "Ransol", "El Tarter", "Grau Roig", "Pessons", "Incles", "Meritxell", "Els Plans",
    "Aixovall", "Borda", "Vila", "Mas de Ribafeta", "L'Aldosa", "Engolasters", "Les Bons", "Prats", "Sispony", "Anyós",
    "Segudet", "Molleres", "Escàs", "Mas d'Alins", "Cortals d'Encamp", "Grau dels Cortals", "Pla de l'Estany", "Els Cortals", "Ransol", "Bordes d'Envalira",
    "Coll d'Ordino", "Pic de Casamanya", "Pic del Comapedrosa", "Estanys de Tristaina", "Sorteny", "La Rabassa", "Naturlandia", "Erts", "La Margineda", "Santa Coloma",
    "Pont de la Tosca", "Andorra Park Hotel", "Caldea", "Madriu-Perafita-Claror", "Casa de la Vall", "Pont de Paris", "Pont d'Engordany", "Pont de la Margineda", "Roc d'Enclar", "Sant Joan de Caselles",
    "Santa Coloma Church", "Sant Esteve Church", "Sant Andreu Church", "Sant Martí Church", "Sant Miquel Church", "Sant Climent Church", "Sant Romà Church", "Santa Eulàlia Church", "Sant Serni Church", "Sant Cristòfol Church",
    "Casa Rull", "Casa d'Areny-Plandolit", "Museu Nacional de l'Automòbil", "Museu del Perfum", "Museu Postal", "Centre de Natura de la Cortinada", "Interpretació de la Natura", "Museu de la Miniatura", "Museu del Còmic", "Museu Carmen Thyssen",
    "Palau de Gel", "Complex Esportiu Serradells", "Camp de Futbol d'Andorra", "Estadi Comunal", "Centre Esportiu dels Serradells", "Piscines Comunals", "Palau d'Esports", "Tennis Club Vallnord", "Club de Golf", "Escola Esquí Soldeu",
    "Luanda", "Huambo", "Lobito", "Benguela", "Kuito", "Lubango", "Malanje", "Namibe", "Soyo", "Cabinda",
    "Uíge", "Saurimo", "Sumbe", "Menongue", "Lucapa", "Caxito", "Kuando Kubango", "Ondjiva", "N'dalatando", "M'banza-Kongo",
    "Dundo", "Tombua", "Porto Amboim", "Camabatela", "Caluquembe", "Chibia", "Matala", "Quilengues", "Humpata", "Gambos",
    "Cahama", "Cuvelai", "Namacunde", "Ombadja", "Cuanhama", "Calai", "Curoca", "Cuangar", "Rivungo", "Dirico",
    "Mavinga", "Cuchi", "Cuemba", "Longa", "Bailundo", "Cachiungo", "Londuimbali", "Mungo", "Chicala-Cholohanga", "Caála",
    "Longonjo", "Ekunha", "Alto Hama", "Chitembo", "Katabola", "Ukuma", "Tchicala-Tcholoanga", "Bocoio", "Chongoroi", "Ganda",
    "Porto Amboim", "Balombo", "Baía Farta", "Catumbela", "Cubal", "Caimbambo", "Chongoroi", "Ganda", "Bocoio", "Balombo",
    "Camacupa", "Cangandala", "Caombo", "Cahombo", "Cacuso", "Kiwaba Nzogi", "Luquembo", "Marimba", "Massango", "Mucari",
    "Quela", "Quirima", "Calandula", "Kunda-dia-Base", "Lemba", "Lucala", "Ngonguembo", "Xa-Muteba", "Banga", "Pango Aluquém",
    "Kambundi-Catembo", "Kaombo", "Songo", "Kiuaba", "Milando", "Alto Cuilo", "Cuango", "Xá-Muteba", "Lubalo", "Chitato",
    "St. John's", "All Saints", "Liberta", "Potter's Village", "Bolans", "Swetes", "Parham", "English Harbour", "Falmouth", "Willikies",
    "Piggotts", "Five Islands", "Jennings", "Cedar Grove", "Freetown", "Old Road", "Johnson's Point", "Urlings", "Bendals", "Dickenson Bay",
    "Runaway Bay", "Hodges Bay", "Crosbies", "Barnes Hill", "Yorks", "Villa", "Gambles", "Buckleys", "Sea View Farm", "Newfield",
    "Bethesda", "Crab Hill", "John Hughes", "Marble Hill", "McNish Mountain", "Orange Valley", "Paynters", "Richland Park", "Tomlinson",
    "Barbuda", "Codrington", "Dulcina", "Spanish Point", "Goat Island", "Bird Island", "Long Island", "Green Island", "Great Bird Island", "Hell's Gate",
    "Two Foot Bay", "Palmetto Point", "Coco Point", "River Landing", "Low Bay", "Pink Sand Beach", "Castle Hill", "Darby Cave", "Indian Town",
    "Martello Tower", "The Caves", "Frigate Bird Sanctuary", "Cedar Tree Point", "Highland House", "Barbuda Highlands", "Codrington Lagoon", "Gravenor Bay", "Rubbish Bay",
    "Devil's Bridge", "Betty's Hope", "Shirley Heights", "Nelson's Dockyard", "Clarence House", "Dow's Hill", "Fig Tree Drive", "Rendezvous Bay", "Half Moon Bay", "Long Bay",
    "Darkwood Beach", "Ffryes Beach", "Valley Church Beach", "Jolly Beach", "Hawksbill Beach", "Eden Island", "Rat Island", "Maiden Island", "Redhead Island", "York Island",
    "Crump Island", "Rabbit Island", "Pelican Island", "Lobster Island", "Sandy Island", "Deep Bay", "Five Islands Harbour", "Nonsuch Bay", "Indian Creek", "Willoughby Bay",
    "Buenos Aires", "Córdoba", "Rosario", "Mendoza", "San Miguel de Tucumán", "La Plata", "Mar del Plata", "Salta", "Santa Fe", "San Juan",
    "Resistencia", "Neuquén", "Santiago del Estero", "Corrientes", "Posadas", "Bahía Blanca", "Paraná", "Formosa", "San Luis", "La Rioja",
    "Catamarca", "Río Gallegos", "Santa Rosa", "San Salvador de Jujuy", "Ushuaia", "San Rafael", "Tandil", "Río Cuarto", "Comodoro Rivadavia", "Concordia",
    "San Nicolás de los Arroyos", "San Fernando del Valle de Catamarca", "Quilmes", "Lanús", "General San Martín", "Lomas de Zamora", "Almirante Brown", "Merlo", "Morón", "Tigre",
    "Malvinas Argentinas", "San Isidro", "Esteban Echeverría", "La Matanza", "Florencio Varela", "Berazategui", "Avellaneda", "Vicente López", "Tres de Febrero", "Hurlingham",
    "Ituzaingó", "José C. Paz", "San Fernando", "Escobar", "Ezeiza", "Pilar", "Moreno", "General Rodríguez", "Luján", "Mercedes",
    "Chivilcoy", "Pergamino", "Junín", "Azul", "Olavarría", "Pehuajó", "Trenque Lauquen", "Bolívar", "Balcarce", "Necochea",
    "Tres Arroyos", "Coronel Suárez", "Pigüé", "General Villegas", "Carlos Casares", "Lincoln", "25 de Mayo", "Bragado", "Chacabuco", "Salto",
    "Arrecifes", "San Pedro", "Baradero", "Zárate", "Campana", "San Antonio de Areco", "Carmen de Areco", "Capitán Sarmiento", "Rojas", "Colón",
    "Pergamino", "San Nicolás", "Ramallo", "San Lorenzo", "Puerto San Martín", "Fray Luis Beltrán", "Villa Gobernador Gálvez", "Pérez", "Granadero Baigorria", "Capitán Bermúdez",
    "Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan", "Abovyan", "Kapan", "Armavir", "Gavar", "Artashat",
    "Goris", "Ashtarak", "Sevan", "Charentsavan", "Dilijan", "Ijevan", "Alaverdi", "Kajaran", "Masis", "Ararat",
    "Sisian", "Yeghegnadzor", "Tashir", "Spitak", "Vardenis", "Berd", "Noyemberyan", "Chambarak", "Tumanyan", "Akhtala",
    "Metsamor", "Artik", "Maralik", "Aparan", "Talin", "Vedi", "Nor Hachn", "Jermuk", "Tsaghkadzor", "Arzni",
    "Agarak", "Meghri", "Dastakert", "Shahumyan", "Nor Kharberd", "Lchashen", "Martuni", "Getashen", "Sarukhan", "Lichk",
    "Dzoraghp", "Artsvaberd", "Khachik", "Garni", "Bjni", "Aghveran", "Meghradzor", "Arzakan", "Byureghavan", "Lusagyugh",
    "Aragats", "Sasunik", "Oshakan", "Voskevaz", "Parpi", "Ashtarak", "Ushi", "Karmrashen", "Aygek", "Aygavan",
    "Irind", "Yeghipatrush", "Kaqavaberd", "Akunq", "Aghdzk", "Arakelots", "Shirakamut", "Pemzashen", "Fioletovo", "Arevashat",
    "Lernahovit", "Hovtashen", "Tsaghkashen", "Anipemza", "Arevabuyr", "Aragatsavan", "Berdashen", "Dzoraghp", "Hoktemberyan", "Hartagyugh",
    "Lernarot", "Antaramej", "Hartavan", "Mrgavet", "Noravan", "Arzakan", "Tsaghkunk", "Aghtsk", "Garnahovit", "Burastan",
    "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Newcastle", "Canberra", "Wollongong", "Logan City",
    "Geelong", "Hobart", "Townsville", "Cairns", "Toowoomba", "Darwin", "Launceston", "Ballarat", "Bendigo", "Albury",
    "Mandurah", "Latrobe City", "Mackay", "Rockhampton", "Bunbury", "Bundaberg", "Wagga Wagga", "Hervey Bay", "Mildura", "Shepparton",
    "Port Macquarie", "Gladstone", "Tamworth", "Traralgon", "Orange", "Dubbo", "Geraldton", "Nowra", "Warrnambool", "Bathurst",
    "Warragul", "Kalgoorlie", "Devonport", "Mount Gambier", "Lismore", "Nelson Bay", "Moe", "Alice Springs", "Wodonga", "Sunbury",
    "Melton", "Maryborough", "Cranbourne", "Frankston", "Pakenham", "Craigieburn", "Werribee", "Dandenong", "Casey", "Whittlesea",
    "Hume", "Wyndham", "Monash", "Knox", "Maroondah", "Whitehorse", "Boroondara", "Glen Eira", "Stonnington", "Port Phillip",
    "Yarra", "Melbourne", "Banyule", "Darebin", "Moreland", "Moonee Valley", "Maribyrnong", "Hobsons Bay", "Brimbank", "Melton",
    "Macedon Ranges", "Mitchell", "Mornington Peninsula", "Cardinia", "Bass Coast", "South Gippsland", "Baw Baw", "Wellington", "East Gippsland", "Towong",
    "Alpine", "Indigo", "Wangaratta", "Benalla", "Strathbogie", "Mansfield", "Murrindindi", "Nillumbik", "Yarra Ranges", "Surf Coast",
    "Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Sankt Pölten", "Dornbirn",
    "Wiener Neustadt", "Steyr", "Feldkirch", "Bregenz", "Leonding", "Klosterneuburg", "Baden", "Wolfsberg", "Leoben", "Krems",
    "Traun", "Amstetten", "Kapfenberg", "Mödling", "Hallein", "Kufstein", "Traiskirchen", "Schwechat", "Braunau am Inn", "Stockerau",
    "Saalfelden", "Ansfelden", "Tulln", "Hohenems", "Spittal an der Drau", "Telfs", "Ternitz", "Perchtoldsdorf", "Hall in Tirol", "Lustenau",
    "Sankt Veit an der Glan", "Gmunden", "Wörgl", "Schwaz", "Hard", "Vöcklabruck", "Lienz", "Rankweil", "Hollabrunn", "Enns",
    "Brunn am Gebirge", "Ried im Innkreis", "Bad Ischl", "Götzis", "Sankt Johann im Pongau", "Gänserndorf", "Bischofshofen", "Eisenstadt", "Mistelbach", "Waidhofen an der Ybbs",
    "Korneuburg", "Neunkirchen", "Groß-Enzersdorf", "Seekirchen am Wallersee", "Sankt Andrä", "Steyregg", "Eugendorf", "Grödig", "Wals-Siezenheim", "Bergheim",
    "Götzendorf an der Leitha", "Himberg", "Fischamend", "Gerasdorf bei Wien", "Deutsch-Wagram", "Ebreichsdorf", "Guntramsdorf", "Laxenburg", "Achau", "Maria Enzersdorf",
    "Henndorf am Wallersee", "Oberndorf bei Salzburg", "Eugendorf", "Elsbethen", "Koppl", "Fuschl am See", "Sankt Gilgen", "Strobl", "Mondsee", "Innerschwand am Mondsee",
    "Zell am See", "Mittersill", "Tamsweg", "Sankt Michael im Lungau", "Radstadt", "Altenmarkt im Pongau", "Flachau", "Wagrain", "Sankt Johann im Pongau", "Schwarzach im Pongau",
    "Baku", "Ganja", "Sumqayit", "Mingachevir", "Qazax", "Shirvan", "Shaki", "Yevlax", "Lankaran", "Nakhchivan",
    "Shamakhi", "Quba", "Ismayilli", "Agdam", "Fuzuli", "Jabrayil", "Zangilan", "Qubadli", "Lachin", "Shusha",
    "Khankendi", "Aghdam", "Tartar", "Barda", "Beylagan", "Imishli", "Sabirabad", "Saatli", "Hajigabul", "Kurdamir",
    "Aghjabadi", "Zardab", "Ujar", "Goychay", "Agdash", "Qabala", "Oghuz", "Shaki", "Zagatala", "Qax",
    "Balakan", "Qusar", "Khachmaz", "Shabran", "Siyazan", "Davachi", "Quba", "Gusar", "Khizi", "Sumqayit",
    "Absheron", "Khirdalan", "Mardakan", "Bilgah", "Nardaran", "Pirallahi", "Ramany", "Sabunchu", "Surakhani", "Yasamal",
    "Nasimi", "Narimanov", "Nizami", "Binagadi", "Khatai", "Sabail", "Pirallahi", "Qaradag", "Sadarak", "Ordubad",
    "Julfa", "Babak", "Sharur", "Kangarli", "Shahbuz", "Culfa", "Masalli", "Yardimli", "Jalilabad", "Lerik",
    "Astara", "Bilasuvar", "Neftchala", "Salyan", "Ali Bayramli", "Shirvan", "Hajigabul", "Gobustan", "Madrasa", "Shamakhi",
    "Aghsu", "Ismayilli", "Qabala", "Oghuz", "Shaki", "Zagatala", "Qax", "Balakan", "Qusar", "Khachmaz"
  ]
