export const weatherInfo = {
    "-50--15": {
        day: {
            image: "extreme-freeze.png",
            alt: "Extreme freezing cold (Day)",
            note: "Dangerously cold ❄️. Stay indoors if possible!",
        },
        night: {
            image: "extreme-freeze-night.jpg",
            alt: "Extreme freezing cold (Night)",
            note: "Freezing night ❄️. Stay warm and avoid going out!",
        },
    },
    "-15--10": {
        day: {
            image: "very-cold.png",
            alt: "Very cold weather (Day)",
            note: "Very cold! Dress in layers and cover up.",
        },
        night: {
            image: "very-cold-night.jpg",
            alt: "Very cold weather (Night)",
            note: "Very cold night 🌙. Extra blankets recommended.",
        },
    },
    "-10--5": {
        day: {
            image: "cold.png",
            alt: "Cold temperature (Day)",
            note: "Cold weather, wear a warm jacket.",
        },
        night: {
            image: "cold-night.jpg",
            alt: "Cold temperature (Night)",
            note: "Chilly night, wear thick clothes to stay warm.",
        },
    },
    "-5-0": {
        day: {
            image: "chilly.png",
            alt: "Chilly near freezing (Day)",
            note: "Chilly, gloves and hats recommended.",
        },
        night: {
            image: "chilly-night.jpg",
            alt: "Chilly near freezing (Night)",
            note: "Cold night near freezing ❄️. Keep warm indoors.",
        },
    },
    "0-5": {
        day: {
            image: "cool.png",
            alt: "Cool temperature (Day)",
            note: "Cool weather. Light jacket needed.",
        },
        night: {
            image: "cool-night.jpg",
            alt: "Cool temperature (Night)",
            note: "Cool night, keep a blanket handy.",
        },
    },
    "5-10": {
        day: {
            image: "mild-cool.png",
            alt: "Mildly cool (Day)",
            note: "Mildly cool, a sweater should be fine.",
        },
        night: {
            image: "mild-cool-night.jpg",
            alt: "Mildly cool (Night)",
            note: "Slightly cold night, sweater or light blanket recommended.",
        },
    },
    "10-15": {
        day: {
            image: "pleasant.png",
            alt: "Pleasant weather (Day)",
            note: "Pleasant and fresh, great for a walk outside.",
        },
        night: {
            image: "pleasant-night.jpg",
            alt: "Pleasant weather (Night)",
            note: "Comfortable evening, perfect for a night stroll.",
        },
    },
    "15-20": {
        day: {
            image: "warm.png",
            alt: "Warm weather (Day)",
            note: "Mildly cool 🌤️. Feels nice and a bit fresh outside.",
        },
        night: {
            image: "warm-night.jpg",
            alt: "Warm weather (Night)",
            note: "Cool night 🌙. A sweater or blanket may be needed.",
        },
    },
    "20-25": {
        day: {
            image: "comfortably-warm.png",
            alt: "Comfortably warm (Day)",
            note: "Nice and warm, perfect for outdoor activities.",
        },
        night: {
            image: "comfortably-warm-night.jpg",
            alt: "Comfortably warm (Night)",
            note: "Warm night 🌙. A light breeze keeps it nice.",
        },
    },
    "25-30": {
        day: {
            image: "hot.png",
            alt: "Hot temperature (Day)",
            note: "Hot weather 🌞, stay hydrated.",
        },
        night: {
            image: "hot-night.jpg",
            alt: "Hot temperature (Night)",
            note: "Warm night, keep hydrated and cool.",
        },
    },
    "30-35": {
        day: {
            image: "very-hot.png",
            alt: "Very hot weather (Day)",
            note: "Very hot! Avoid being outside too long.",
        },
        night: {
            image: "very-hot-night.jpg",
            alt: "Very hot weather (Night)",
            note: "Hot evening 🌙. Use fans or AC to stay cool.",
        },
    },
    "35-50": {
        day: {
            image: "extreme-heat.png",
            alt: "Extreme heat (Day)",
            note: "Extreme heat 🌋. Stay cool and drink lots of water!",
        },
        night: {
            image: "extreme-heat-night.jpg",
            alt: "Extreme heat (Night)",
            note: "Very hot night 🌙. Avoid heavy activities and stay hydrated.",
        },
    },
};

export const rainInfo = {
    "0-1": {
        day: {
            image: "light-rain.png",
            alt: "Light rain (Day)",
            note: "Drizzle ☔. A light umbrella is enough.",
        },
        night: {
            image: "light-rain-night.jpg",
            alt: "Light rain (Night)",
            note: "Light showers 🌧️. Roads may be a little slippery.",
        },
    },
    "1-5": {
        day: {
            image: "moderate-rain.png",
            alt: "Moderate rain (Day)",
            note: "Moderate rain ☔. Take a proper umbrella or raincoat.",
        },
        night: {
            image: "moderate-rain-night.jpg",
            alt: "Moderate rain (Night)",
            note: "Steady rainfall 🌧️. Drive carefully.",
        },
    },
    "5-20": {
        day: {
            image: "heavy-rain.png",
            alt: "Heavy rain (Day)",
            note: "Heavy rain 🌧️. Stay safe, possible waterlogging.",
        },
        night: {
            image: "heavy-rain-night.jpg",
            alt: "Heavy rain (Night)",
            note: "Strong rainfall 🌧️. Avoid unnecessary travel.",
        },
    },
    "20-100": {
        day: {
            image: "extreme-rain.png",
            alt: "Extreme rain (Day)",
            note: "Extreme rain ⛈️. Flooding possible, stay indoors!",
        },
        night: {
            image: "extreme-rain-night.jpg",
            alt: "Extreme rain (Night)",
            note: "Dangerous rainfall ⛈️. Avoid going outside.",
        },
    },
};

export const cities = [
    "Aalborg",
    "Aalen",
    "Aarau",
    "Aarhus",
    "Abadan",
    "Aberdeen",
    "Abilene",
    "Abington",
    "Abu Dhabi",
    "Abuja",
    "Acapulco",
    "Accra",
    "Adelaide",
    "Aden",
    "Adana",
    "Addis Ababa",
    "Agadir",
    "Agra",
    "Ahmedabad",
    "Aichi",
    "Akron",
    "Albany",
    "Albuquerque",
    "Aleppo",
    "Alexandria",
    "Algiers",
    "Alicante",
    "Almaty",
    "Amarillo",
    "Amman",
    "Amsterdam",
    "Anchorage",
    "Ankara",
    "Antalya",
    "Antwerp",
    "Apia",
    "Arad",
    "Arequipa",
    "Arlington",
    "Asheville",
    "Asmara",
    "Astana",
    "Asunción",
    "Athens",
    "Atlanta",
    "Atlantic City",
    "Auckland",
    "Augusta",
    "Aurora",
    "Austin",
    "Avignon",
    "Ayacucho",
    "Azusa",
    "Aachen",
    "Abbotsford",
    "Abha",
    "Abidjan",
    "Abomey",
    "Abruzzi",
    "Acajutla",
    "Acarigua",
    "Accrington",
    "Acheng",
    "Achinsk",
    "Acireale",
    "Acton",
    "Ada",
    "Adak",
    "Adams",
    "Addison",
    "Adilabad",
    "Admiralty",
    "Adrian",
    "Afula",
    "Agadez",
    "Agartala",
    "Agen",
    "Agnone",
    "Agrigento",
    "Aguascalientes",
    "Ahvaz",
    "Aiken",
    "Aintab",
    "Airdrie",
    "Aitkin",
    "Aix-en-Provence",
    "Ajaccio",
    "Ajmer",
    "Akita",
    "Akola",
    "Aktau",
    "Aktobe",
    "Al Ain",
    "Al Khobar",
    "Al Mukalla",
    "Ala",
    "Alabama City",
    "Alameda",
    "Alamogordo",
    "Alamosa",
    "Alba Iulia",
    "Albacete",
    "Alban",
    "Albion",
    "Albury",
    "Alcala",
    "Alcamo",
    "Alcobaça",
    "Aldine",
    "Alert",
    "Alessandria",
    "Alesund",
    "Alexander City",
    "Alfenas",
    "Alghero",
    "Algoma",
    "Alhambra",
    "Alice",
    "Alice Springs",
    "Aliquippa",
    "Alkmaar",
    "Allahabad",
    "Allentown",
    "Alliance",
    "Almada",
    "Almeria",
    "Alofi",
    "Alpena",
    "Alpine",
    "Altoona",
    "Alvin",
    "Amadeus",
    "Amalfi",
    "Amanda",
    "Amarante",
    "Amberg",
    "Ambler",
    "Amboise",
    "Ambon",
    "Amersfoort",
    "Ames",
    "Amherst",
    "Amiens",
    "Amritsar",
    "Amstetten",
    "Anaheim",
    "Anapa",
    "Anatolia",
    "Ancona",
    "Anderson",
    "Andorra la Vella",
    "Angers",
    "Anghiari",
    "Angola",
    "Angra",
    "Angren",
    "Ani",
    "Aniche",
    "Anjalankoski",
    "Ann Arbor",
    "Annaba",
    "Annecy",
    "Anniston",
    "Anqing",
    "Ansan",
    "Anshan",
    "Ansonia",
    "Antananarivo",
    "Anthony",
    "Antioch",
    "Antofagasta",
    "Anyang",
    "Anzio",
    "Aomori",
    "Aparecida",
    "Apeldoorn",
    "Apex",
    "Appleton",
    "Apucarana",
    "Aquila",
    "Arabkir",
    "Aracaju",
    "Aragua",
    "Arak",
    "Arandis",
    "Aranjuez",
    "Arapahoe",
    "Araras",
    "Arapiraca",
    "Arbroath",
    "Arcadia",
    "Archangel",
    "Archer City",
    "Arco",
    "Ardabil",
    "Arden Hills",
    "Ardmore",
    "Arecibo",
    "Arezzo",
    "Argentina",
    "Argostoli",
    "Arhus",
    "Arima",
    "Arkansas City",
    "Arles",
    "Arlington Heights",
    "Armagh",
    "Armavir",
    "Armenia",
    "Arnhem",
    "Arnold",
    "Arras",
    "Arthur",
    "Artesia",
    "Arusha",
    "Arvada",
    "Asahikawa",
    "Asansol",
    "Asbury Park",
    "Ascoli Piceno",
    "Ashdod",
    "Ashford",
    "Ashgabat",
    "Ashkelon",
    "Ashland",
    "Ashtabula",
    "Ashton",
    "Aspen",
    "Astrakhan",
    "Aswan",
    "Asyut",
    "Atakpame",
    "Atascadero",
    "Atbara",
    "Atchison",
    "Athabasca",
    "Athens",
    "Athlone",
    "Atizapan",
    "Atlantic Beach",
    "Atmore",
    "Attleboro",
    "Atwater",
    "Auburn",
    "Audubon",
    "Augsburg",
    "Augusta",
    "Aurillac",
    "Ausonia",
    "Austell",
    "Auxerre",
    "Avalon",
    "Avenal",
    "Aversa",
    "Avesta",
    "Aviemore",
    "Aviles",
    "Avondale",
    "Axminster",
    "Ayacucho",
    "Aydin",
    "Aylesbury",
    "Ayer",
    "Ayutthaya",
    "Azogues",
    "Azores",
    "Aztec",
    "Azul",
    "Abakan",
    "Abancay",
    "Abaetetuba",
    "Abakan",
    "Abandze",
    "Abashiri",
    "Abastumani",
    "Abbotsford",
    "Abbeville",
    "Abbott",
    "Abdera",
    "Abengourou",
    "Aberaeron",
    "Aberdare",
    "Aberdour",
    "Aberfeldy",
    "Abergavenny",
    "Abergele",
    "Aberlour",
    "Abernathy",
    "Abertillery",
    "Aberystwyth",
    "Abha",
    "Abilene",
    "Abingdon",
    "Abington",
    "Abiquiu",
    "Abitibi",
    "Abingworth",
    "Abisko",
    "Abita Springs",
    "Abkhazia",
    "Abomsa",
    "Abony",
    "Aboutiou",
    "Abovyan",
    "Abra",
    "Abrams",
    "Abrantes",
    "Absecon",
    "Absarokee",
    "Abu Simbel",
    "Abuja",
    "Abun",
    "Aburi",
    "Aby",
    "Abydos",
    "Acacia Ridge",
    "Acambaro",
    "Acarau",
    "Acari",
    "Accadia",
    "Accomac",
    "Achern",
    "Acheville",
    "Achille",
    "Achimota",
    "Achonry",
    "Acme",
    "Acoma",
    "Aconteceu",
    "Acqui Terme",
    "Acra",
    "Acri",
    "Acrux",
    "Acteal",
    "Actopan",
    "Acushnet",
    "Adairsville",
    "Adalaj",
    "Adam",
    "Adamawa",
    "Adamsville",
    "Adamstown",
    "Adana",
    "Adangme",
    "Adapazari",
    "Adar",
    "Addington",
    "Addlestone",
    "Ade",
    "Adelanto",
    "Adelfia",
    "Aden",
    "Adera",
    "Adger",
    "Adhara",
    "Adilcevaz",
    "Adinkerke",
    "Adirondack",
    "Adis Zemen",
    "Adjame",
    "Adjuntas",
    "Adler",
    "Admiral",
    "Ado",
    "Adobe",
    "Adolfo",
    "Adopha",
    "Adra",
    "Adrar",
    "Adre",
    "Adrian",
    "Adria",
    "Adrianople",
    "Adrogué",
    "Adsit",
    "Advance",
    "Adventdalen",
    "Aé",
    "Aegean",
    "Aesch",
    "Afantou",
    "Afar",
    "Affoltern",
    "Afghoy",
    "Afif",
    "Afipsky",
    "Afissos",
    "Afognak",
    "Afonso Cláudio",
    "Afragola",
    "Afton",
    "Agadir",
    "Agana",
    "Agapovo",
    "Agartala",
    "Agathonisi",
    "Agats",
    "Agaue",
    "Agawam",
    "Agency",
    "Agen",
    "Aggeneys",
    "Aghios Nikolaos",
    "Agigea",
    "Agin-Buryat",
    "Agios",
    "Agira",
    "Agjabadi",
    "Aglantzia",
    "Agnone",
    "Agogo",
    "Agonges",
    "Agoo",
    "Agordat",
    "Agra",
    "Agremont",
    "Agrinion",
    "Agropoli",
    "Agua",
    "Aguacatan",
    "Aguada",
    "Aguadilla",
    "Aguaí",
    "Aguapei",
    "Aguascalientes",
    "Agueda",
    "Aguilar",
    "Aguimes",
    "Aguilas",
    "Aguirre",
    "Agung",
    "Aguscalientes",
    "Ahangaran",
    "Ahaus",
    "Ahipara",
    "Ahlat",
    "Ahnatal",
    "Ahoskie",
    "Ahuachapán",
    "Ahuas",
    "Ahvaz",
    "Aibonito",
    "Aichi",
    "Aigues-Mortes",
    "Aihole",
    "Ain Beida",
    "Ain Defla",
    "Ain Salah",
    "Ain Temouchent",
    "Ainsa",
    "Aioi",
    "Aipe",
    "Aiquile",
    "Airasca",
    "Aire-sur-l'Adour",
    "Airlie Beach",
    "Airway Heights",
    "Aisén",
    "Aitkin",
    "Aiud",
    "Aiun",
    "Aizenay",
    "Ajax",
    "Ajdabiya",
    "Ajdir",
    "Ajka",
    "Ajloun",
    "Ajman",
    "Ajmer",
    "Ajodhya",
    "Akabira",
    "Akagi",
    "Akaki",
    "Akan",
    "Akashi",
    "Akdagmadeni",
    "Akim Oda",
    "Akita",
    "Akkol",
    "Akmola",
    "Akola",
    "Akosombo",
    "Akron",
    "Akrotiri",
    "Aksaray",
    "Aksu",
    "Akita",
    "Aksum",
    "Aktau",
    "Akure",
    "Akyab",
    "Alabama",
    "Alachua",
    "Aladdin",
    "Alagir",
    "Alagoinhas",
    "Alajuela",
    "Alamagan",
    "Alamance",
    "Alamar",
    "Alaminos",
    "Alamo",
    "Alamogordo",
    "Alamosa",
    "Aland",
    "Alanya",
    "Alapayevsk",
    "Alaró",
    "Alaska",
    "Alatri",
    "Alatyr",
    "Alba",
    "Albacete",
    "Albaicín",
    "Alban",
    "Albanel",
    "Albano Laziale",
    "Albany",
    "Albenga",
    "Alberga",
    "Albi",
    "Albion",
    "Alboraya",
    "Albuquerque",
    "Albury",
    "Alcala",
    "Alcantara",
    "Alcaraz",
    "Alcester",
    "Alcobaça",
    "Alcobendas",
    "Alcoi",
    "Alcorcón",
    "Alcoy",
    "Alcúdia",
    "Aldabra",
    "Aldan",
    "Aldara",
    "Aldea",
    "Aldershot",
    "Aledo",
    "Alegrete",
    "Aleksandrovsk",
    "Alem",
    "Alemdar",
    "Alençon",
    "Aleppo",
    "Alert",
    "Ales",
    "Alesund",
    "Alexander",
    "Alexandroupoli",
    "Alexania",
    "Alfafar",
    "Alfenas",
    "Alfonso",
    "Alford",
    "Alfred",
    "Alfter",
    "Algeciras",
    "Algeria",
    "Algiers",
    "Alhama",
    "Alhambra",
    "Alice",
    "Alicudi",
    "Aligudarz",
    "Alijo",
    "Alingsås",
    "Aliquippa",
    "Alisaih",
    "Aliso Viejo",
    "Aljaraque",
    "Alkmaar",
    "Allahabad",
    "Allauch",
    "Allegany",
    "Allen",
    "Allentown",
    "Alliance",
    "Alloa",
    "Allouez",
    "Alma",
    "Almada",
    "Almadén",
    "Almagro",
    "Almansa",
    "Almargen",
    "Almaty",
    "Almdorf",
    "Almeirim",
    "Almelo",
    "Almendralejo",
    "Almeria",
    "Almodóvar",
    "Almuñécar",
    "Alofi",
    "Alor Setar",
    "Alpena",
    "Alpharetta",
    "Alpine",
    "Alsace",
    "Altamont",
    "Altamonte Springs",
    "Altamura",
    "Altay",
    "Altdorf",
    "Altenkirchen",
    "Altoona",
    "Altus",
    "Alushta",
    "Alvear",
    "Alverca",
    "Alvin",
    "Alwar",
    "Alzira",
    "Amadiya",
    "Amagasaki",
    "Amakusa",
    "Amalfi",
    "Amanda",
    "Amangeldy",
    "Amanzimtoti",
    "Amapala",
    "Amara",
    "Amarante",
    "Amarillo",
    "Amasia",
    "Amatitlan",
    "Amawalk",
    "Amazon",
    "Amberg",
    "Amberley",
    "Ambler",
    "Ambleside",
    "Amboise",
    "Ambon",
    "Ambositra",
    "Ambovombe",
    "Ambridge",
    "Amelia",
    "American Fork",
    "Americus",
    "Ames",
    "Amesbury",
    "Amherst",
    "Amiens",
    "Aminabad",
    "Amirabad",
    "Amityville",
    "Amman",
    "Amol",
    "Ampere",
    "Amposta",
    "Amsterdam",
    "Amur",
    "Ana",
    "Anaco",
    "Anacortes",
    "Anadarko",
    "Anadolu",
    "Anadyr",
    "Anagni",
    "Anaheim",
    "Anajás",
    "Anaklia",
    "Analanjirofo",
    "Anand",
    "Anapa",
    "Anapolis",
    "Anapra",
    "Ancaster",
    "Anchorage",
    "Ancona",
    "Andalusia",
    "Andaman",
    "Andelsbuch",
    "Andenne",
    "Anderson",
    "Andes",
    "Andhra Pradesh",
    "Andimeshk",
    "Andong",
    "Andorra",
    "Andover",
    "Andrassy",
    "Andrews",
    "Andria",
    "Andrijevica",
    "Andujar",
    "Aneby",
    "Anegada",
    "Angers",
    "Anghiari",
    "Anglesey",
    "Anglo",
    "Angostura",
    "Anguilla",
    "Angwin",
    "Aniak",
    "Aniche",
    "Anif",
    "Animo",
    "Anjar",
    "Anjou",
    "Anjuna",
    "Ankapoer",
    "Ankara",
    "Anklam",
    "Ann Arbor",
    "Annaba",
    "Annapolis",
    "Annecy",
    "Anniston",
    "Anqing",
    "Ansbach",
    "Anshan",
    "Ansonia",
    "Antakya",
    "Antananarivo",
    "Antelias",
    "Anthony",
    "Antibes",
    "Anticosti",
    "Antigua",
    "Antioch",
    "Antioquia",
    "Antipolo",
    "Antofagasta",
    "Antonina",
    "Antrim",
    "Antsiranana",
    "Antwerp",
    "Anuradhapura",
    "Anyang",
    "Anyox",
    "Anzio",
    "Anzola",
    "Aomori",
    "Apache",
    "Apalachicola",
    "Aparecida",
    "Apatity",
    "Apatzingán",
    "Apia",
    "Apopa",
    "Appleton",
    "April",
    "Aprilia",
    "Apucaran",
    "Apure",
    "Aqaba",
    "Aqtau",
    "Aqtobe",
    "Aquascalientes",
    "Arab",
    "Arabia",
    "Arabkir",
    "Aracaju",
    "Aracatuba",
    "Aracena",
    "Araguaina",
    ,
    "Arak",
    "Aranda",
    "Arandis",
    "Aranjuez",
    "Arapahoe",
    "Arapiraca",
    "Arapongas",
    "Araras",
    "Ararat",
    "Arauca",
    "Arava",
    "Araxá",
    "Arba Minch",
    "Arbatax",
    "Arbon",
    "Arbroath",
    "Arcachon",
    "Arcadia",
    "Arcanjo",
    "Arcata",
    "Archangel",
    "Arche",
    "Archer",
    "Archidona",
    "Arco",
    "Arcola",
    "Ardabil",
    "Ardales",
    "Ardmore",
    "Arecibo",
    "Arendal",
    "Arequipa",
    "Arezzo",
    "Arganda",
    "Argao",
    "Argentina",
    "Argentia",
    "Argentona",
    "Argos",
    "Argostoli",
    "Argyle",
    "Århus",
    "Arica",
    "Arichat",
    "Ariel",
    "Ariha",
    "Arima",
    "Ariquemes",
    "Arizona",
    "Arjona",
    "Arkansas",
    "Arklow",
    "Arles",
    "Arlington",
    "Arlit",
    "Armagh",
    "Armavir",
    "Armenia",
    "Armentieres",
    "Armidale",
    "Arnold",
    "Arnprior",
    "Arnsberg",
    "Arnstadt",
    "Aroostook",
    "Arpajon",
    "Arrecife",
    "Arroyo",
    "Arta",
    "Artashat",
    "Artesia",
    "Arthur",
    "Artvin",
    "Arusha",
    "Arva",
    "Arvada",
    "Arvika",
    "Asaba",
    "Asahikawa",
    "Asansol",
    "Asaph",
    "Asbury",
    "Ascension",
    "Ascoli",
    "Asenovgrad",
    "Asgabat",
    "Ashbourne",
    "Ashburton",
    "Ashby",
    "Ashdod",
    "Asheville",
    "Ashford",
    "Ashgabat",
    "Ashington",
    "Ashiya",
    "Ashkelon",
    "Ashland",
    "Ashley",
    "Ashtabula",
    "Ashton",
    "Ashville",
    "Asigliano",
    "Asimov",
    "Asit",
    "Asker",
    "Asmara",
    "Asni",
    "Aso",
    "Asosa",
    "Aspen",
    "Asperg",
    "Aspropirgos",
    "Assab",
    "Assam",
    "Assisi",
    "Asten",
    "Astoria",
    "Astrakhan",
    "Asunción",
    "Aswan",
    "Asyut",
    "Atacama",
    "Atakpame",
    "Atami",
    "Atascadero",
    "Atbara",
    "Atchison",
    "Ateca",
    "Aten",
    "Athabasca",
    "Athboy",
    "Athena",
    "Athens",
    "Atherton",
    "Athlone",
    "Atibaia",
    "Atienza",
    "Atirau",
    "Atizapán",
    "Atka",
    "Atlanta",
    "Atlantic",
    "Atlantida",
    "Atlas",
    "Atmore",
    "Atoka",
    "Atsugi",
    "Attawapiskat",
    "Attica",
    "Attleboro",
    "Attnang",
    "Attu",
    "Atwater",
    "Auburn",
    "Auckland",
    "Auderghem",
    "Audubon",
    "Augsburg",
    "Augusta",
    "Auki",
    "Aulnay",
    "Aurangabad",
    "Aurec",
    "Aurillac",
    "Auronzo",
    "Aurora",
    "Ausburg",
    "Ausonia",
    "Austell",
    "Austin",
    "Autun",
    "Auxerre",
    "Avalon",
    "Avarua",
    "Aveiro",
    "Avenal",
    "Avera",
    "Aversa",
    "Avesta",
    "Avezzano",
    "Aviemore",
    "Avignon",
    "Aviles",
    "Avington",
    "Avlona",
    "Avon",
    "Avondale",
    "Avonlea",
    "Awasa",
    "Awka",
    "Axminster",
    "Ayacucho",
    "Aycliffe",
    "Aydin",
    "Aylesbury",
    "Ayr",
    "Aytos",
    "Ayutthaya",
    "Azamgarh",
    "Azemmour",
    "Azerbaijan",
    "Azogues",
    "Azores",
    "Azov",
    "Aztec",
    "Azua",
    "Azul",
    "Azusa",
    "Baghdad",
    "Bangkok",
    "Barcelona",
    "Beijing",
    "Berlin",
    "Bogotá",
    "Boston",
    "Brisbane",
    "Brussels",
    "Budapest",
    "Buenos Aires",
    "Buffalo",
    "Bangalore",
    "Birmingham",
    "Baltimore",
    "Baton Rouge",
    "Bakersfield",
    "Bristol",
    "Brighton",
    "Bradford",
    "Bordeaux",
    "Bremen",
    "Basel",
    "Bern",
    "Bratislava",
    "Bucharest",
    "Belgrade",
    "Baku",
    "Beirut",
    "Bamako",
    "Brazzaville",
    "Bridgetown",
    "Banjul",
    "Bissau",
    "Belmopan",
    "Bandar Seri Begawan",
    "Boise",
    "Bilbao",
    "Bergamo",
    "Bologna",
    "Bari",
    "Brescia",
    "Bolzano",
    "Brindisi",
    "Benevento",
    "Belluno",
    "Biella",
    "Braga",
    "Brno",
    "Braşov",
    "Burgas",
    "Bournemouth",
    "Bath",
    "Blackpool",
    "Bolton",
    "Blackburn",
    "Burnley",
    "Burton",
    "Bury",
    "Basingstoke",
    "Bangor",
    "Barrow",
    "Barnsley",
    "Ballarat",
    "Bendigo",
    "Bundaberg",
    "Bunbury",
    "Ballina",
    "Broome",
    "Bathurst",
    "Broken Hill",
    "Burnie",
    "Blacktown",
    "Bankstown",
    "Bondi",
    "Bayside",
    "Berwick",
    "Box Hill",
    "Brunswick",
    "Bentleigh",
    "Bulleen",
    "Balwyn",
    "Broadmeadows",
    "Bayswater",
    "Boronia",
    "Bentley",
    "Belmont",
    "Bundoora",
    "Belgrave",
    "Blackburn South",
    "Baulkham Hills",
    "Banksia",
    "Beacon Hill",
    "Bella Vista",
    "Beverly Hills",
    "Bidwill",
    "Birrong",
    "Blackett",
    "Blair Athol",
    "Blaxland",
    "Blue Bay",
    "Bonnyrigg",
    "Bossley Park",
    "Bow Bowing",
    "Bradbury",
    "Breakfast Point",
    "Bringelly",
    "Bundeena",
    "Burwood",
    "Busby",
    "Byford",
    "Banyo",
    "Bardon",
    "Bracken Ridge",
    "Brendale",
    "Bridgeman Downs",
    "Brighton",
    "Broadbeach",
    "Burleigh Heads",
    "Burpengary",
    "Beenleigh",
    "Beaudesert",
    "Bowen",
    "Biloela",
    "Barcaldine",
    "Blackall",
    "Boulia",
    "Bedourie",
    "Birdsville",
    "Burketown",
    "Bamaga",
    "Babinda",
    "Bowen Hills",
    "Bulimba",
    "Balmoral",
    "Banyo",
    "Bardon",
    "Belmont",
    "Bethania",
    "Bracken Ridge",
    "Brendale",
    "Bridgeman Downs",
    "Brighton",
    "Broadbeach Waters",
    "Burleigh Waters",
    "Burpengary East",
    "Beerwah",
    "Bellara",
    "Bongaree",
    "Bribie Island",
    "Bucasia",
    "Burnett Heads",
    "Bargara",
    "Beaconsfield",
    "Berwick",
    "Braeside",
    "Brighton East",
    "Broadmeadows",
    "Brunswick East",
    "Brunswick West",
    "Bulleen",
    "Bundoora",
    "Burwood East",
    "Baxter",
    "Beaumaris",
    "Bentleigh East",
    "Berwick",
    "Beveridge",
    "Bittern",
    "Bonbeach",
    "Boronia",
    "Box Hill North",
    "Box Hill South",
    "Braeside",
    "Broadmeadows",
    "Brooklyn",
    "Briar Hill",
    "Burwood",
    "Bundoora",
    "Burnley",
    "Boroondara",
    "Ballarat Central",
    "Ballarat East",
    "Ballarat North",
    "Bakery Hill",
    "Brown Hill",
    "Buninyong",
    "Ballan",
    "Bacchus Marsh",
    "Bannockburn",
    "Barwon Heads",
    "Batesford",
    "Bellbrae",
    "Belmont",
    "Breakwater",
    "Breamlea",
    "Buckley",
    "Burwood Heights",
    "Ballarat",
    "Benalla",
    "Bendigo",
    "Beechworth",
    "Bright",
    "Bairnsdale",
    "Bass",
    "Belgrave",
    "Berwick",
    "Broadford",
    "Bacchus Marsh",
    "Ballarat",
    "Benalla",
    "Bendigo",
    "Beechworth",
    "Bright",
    "Bairnsdale",
    "Bass",
    "Belgrave",
    "Berwick",
    "Broadford",
    "Ballina",
    "Bathurst",
    "Bega",
    "Bellingen",
    "Bombala",
    "Bourke",
    "Bowral",
    "Broken Hill",
    "Byron Bay",
    "Batemans Bay",
    "Baulkham Hills",
    "Beecroft",
    "Belrose",
    "Bexley",
    "Blacktown",
    "Blaxland",
    "Blue Mountains",
    "Bondi Beach",
    "Bondi Junction",
    "Botany",
    "Brookvale",
    "Burwood",
    "Bankstown",
    "Bass Hill",
    "Berala",
    "Beverly Hills",
    "Birrong",
    "Blacktown",
    "Blakehurst",
    "Bonnyrigg",
    "Bossley Park",
    "Bradbury",
    "Breakfast Point",
    "Brighton-Le-Sands",
    "Burwood",
    "Banksia",
    "Bardwell Park",
    "Bexley",
    "Brighton",
    "Burraneer",
    "Bundeena",
    "Burraneer Bay",
    "Barden Ridge",
    "Belrose",
    "Beacon Hill",
    "Bilgola",
    "Bilgola Plateau",
    "Brookvale",
    "Balgowlah",
    "Balgowlah Heights",
    "Bayview",
    "Belrose",
    "Beacon Hill",
    "Bangor",
    "Barden Ridge",
    "Bundeena",
    "Burraneer",
    "Blakehurst",
    "Brighton-Le-Sands",
    "Beverley Park",
    "Bardwell Park",
    "Bexley",
    "Bexley North",
    "Banksia",
    "Brighton",
    "Burraneer",
    "Bundeena",
    "Burraneer Bay",
    "Barden Ridge",
    "Belrose",
    "Beacon Hill",
    "Bilgola",
    "Bilgola Plateau",
    "Brookvale",
    "Balgowlah",
    "Balgowlah Heights",
    "Bayview",
    "Belrose",
    "Beacon Hill",
    "Bangor",
    "Barden Ridge",
    "Bundeena",
    "Burraneer",
    "Blakehurst",
    "Brighton-Le-Sands",
    "Beverley Park",
    "Bardwell Park",
    "Bexley",
    "Bexley North",
    "Banksia",
    "Bronte",
    "Bondi",
    "Bellevue Hill",
    "Birchgrove",
    "Balmain",
    "Balmain East",
    "Birchgrove",
    "Balmain",
    "Balmain East",
    "Burwood",
    "Berala",
    "Bankstown",
    "Bass Hill",
    "Birrong",
    "Belfield",
    "Belmore",
    "Bankstown",
    "Banksia",
    "Bardwell Park",
    "Bexley",
    "Brighton",
    "Burraneer",
    "Bundeena",
    "Burraneer Bay",
    "Barden Ridge",
    "Bangor",
    "Blakehurst",
    "Brighton-Le-Sands",
    "Beverley Park",
    "Bardwell Park",
    "Bexley",
    "Bexley North",
    "Banksia",
    "Botany",
    "Banksmeadow",
    "Barangaroo",
    "Beaconsfield",
    "Bellevue Hill",
    "Birchgrove",
    "Balmain",
    "Balmain East",
    "Blackwattle Bay",
    "Barangaroo",
    "Balmain",
    "Birchgrove",
    "Birrong",
    "Berala",
    "Bass Hill",
    "Bankstown",
    "Birrong",
    "Bankstown",
    "Bankstown Airport",
    "Bankstown",
    "Bass Hill",
    "Berala",
    "Birrong",
    "Chullora",
    "Bankstown",
    "Bankstown Airport",
    "Blackheath",
    "Blaxland",
    "Blue Mountains",
    "Bowenfels",
    "Bathurst",
    "Blayney",
    "Borenore",
    "Brewongle",
    "Bombala",
    "Bermagui",
    "Batemans Bay",
    "Broulee",
    "Bodalla",
    "Bemboka",
    "Bombala",
    "Berridale",
    "Bungendore",
    "Braidwood",
    "Boorowa",
    "Bowning",
    "Burra",
    "Burrinjuck",
    "Bethungra",
    "Bookham",
    "Bowral",
    "Berrima",
    "Bundanoon",
    "Burradoo",
    "Buxton",
    "Bargo",
    "Bulli",
    "Bellambi",
    "Berkeley",
    "Brownsville",
    "Balgownie",
    "Balgowlah",
    "Bulli",
    "Bellambi",
    "Berkeley",
    "Brownsville",
    "Balgownie",
    "Balgowlah",
    "Ballina",
    "Byron Bay",
    "Bangalow",
    "Brunswick Heads",
    "Billinudgel",
    "Broken Head",
    "Brooklet",
    "Bexhill",
    "Booyong",
    "Bungalow",
    "Bentley",
    "Bogangar",
    "Burringbar",
    "Bilambil",
    "Bilambil Heights",
    "Banora Point",
    "Bomaderry",
    "Berry",
    "Bundanoon",
    "Bowral",
    "Berrima",
    "Burradoo",
    "Buxton",
    "Bargo",
    "Beaconsfield",
    "Bulli",
    "Bellambi",
    "Berkeley",
    "Brownsville",
    "Balgownie",
    "Bateau Bay",
    "Buff Point",
    "Budgewoi",
    "Budgewoi Peninsula",
    "Bateau Bay",
    "Berkeley Vale",
    "Blue Bay",
    "Booragul",
    "Boolaroo",
    "Blackalls Park",
    "Belmont",
    "Belmont North",
    "Belmont South",
    "Bolton Point",
    "Booragul",
    "Boolaroo",
    "Blackalls Park",
    "Belmont",
    "Belmont North",
    "Belmont South",
    "Bolton Point",
    "Branxton",
    "Broke",
    "Bulga",
    "Baerami",
    "Bylong",
    "Bulahdelah",
    "Booral",
    "Bundabah",
    "Bungwahl",
    "Bulahdelah",
    "Booral",
    "Bundabah",
    "Bungwahl",
    "Blackhead",
    "Blueys Beach",
    "Boomerang Beach",
    "Boorowa",
    "Blayney",
    "Bathurst",
    "Bourke",
    "Brewarrina",
    "Broken Hill",
    "Balranald",
    "Barham",
    "Berrigan",
    "Boggabilla",
    "Bingara",
    "Barraba",
    "Bundarra",
    "Bendemeer",
    "Boggabri",
    "Breeza",
    "Blackville",
    "Baan Baa",
    "Bellata",
    "Burren Junction",
    "Binnaway",
    "Baradine",
    "Bogan Gate",
    "Bedgerebong",
    "Borenore",
    "Blayney",
    "Bathurst",
    "Boorowa",
    "Bowral",
    "Berrima",
    "Bundanoon",
    "Burradoo",
    "Buxton",
    "Bargo",
    "Beaconsfield",
    "Bulli",
    "Bellambi",
    "Berkeley",
    "Brownsville",
    "Balgownie",
    "Blackbutt",
    "Bateau Bay",
    "Buff Point",
    "Budgewoi",
    "Budgewoi Peninsula",
    "Bateau Bay",
    "Berkeley Vale",
    "Blue Bay",
    "Booragul",
    "Boolaroo",
    "Blackalls Park",
    "Belmont",
    "Belmont North",
    "Belmont South",
    "Bolton Point",
    "Branxton",
    "Broke",
    "Bulga",
    "Baerami",
    "Bylong",
    "Bulahdelah",
    "Booral",
    "Bundabah",
    "Bungwahl",
    "Blackhead",
    "Blueys Beach",
    "Boomerang Beach",
    "Bonny Hills",
    "Bonville",
    "Bellingen",
    "Bowraville",
    "Boambee",
    "Boambee East",
    "Bucca",
    "Brooklana",
    "Brierfield",
    "Bellingen",
    "Bowraville",
    "Boambee",
    "Boambee East",
    "Bucca",
    "Brooklana",
    "Brierfield",
    "Byron Bay",
    "Bangalow",
    "Brunswick Heads",
    "Billinudgel",
    "Broken Head",
    "Brooklet",
    "Bexhill",
    "Booyong",
    "Bungalow",
    "Bentley",
    "Bogangar",
    "Burringbar",
    "Bilambil",
    "Bilambil Heights",
    "Banora Point",
    "Brisbane",
    "Bundaberg",
    "Burleigh Heads",
    "Broadbeach",
    "Burpengary",
    "Beenleigh",
    "Beaudesert",
    "Bowen",
    "Biloela",
    "Barcaldine",
    "Blackall",
    "Boulia",
    "Bedourie",
    "Birdsville",
    "Burketown",
    "Bamaga",
    "Babinda",
    "Bowen Hills",
    "Bulimba",
    "Balmoral",
    "Banyo",
    "Bardon",
    "Belmont",
    "Bethania",
    "Bracken Ridge",
    "Brendale",
    "Bridgeman Downs",
    "Brighton",
    "Broadbeach Waters",
    "Burleigh Waters",
    "Burpengary East",
    "Beerwah",
    "Bellara",
    "Bongaree",
    "Bribie Island",
    "Bucasia",
    "Burnett Heads",
    "Bargara",
    "Beaconsfield",
    "Berwick",
    "Braeside",
    "Brighton East",
    "Broadmeadows",
    "Brunswick East",
    "Brunswick West",
    "Bulleen",
    "Bundoora",
    "Burwood East",
    "Baxter",
    "Beaumaris",
    "Bentleigh East",
    "Berwick",
    "Beveridge",
    "Bittern",
    "Bonbeach",
    "Boronia",
    "Box Hill North",
    "Box Hill South",
    "Braeside",
    "Braybrook",
    "Broadmeadows",
    "Brooklyn",
    "Briar Hill",
    "Burwood",
    "Bundoora",
    "Burnley",
    "Boroondara",
    "Ballarat Central",
    "Ballarat East",
    "Ballarat North",
    "Bakery Hill",
    "Brown Hill",
    "Buninyong",
    "Ballan",
    "Bacchus Marsh",
    "Bannockburn",
    "Barwon Heads",
    "Batesford",
    "Bellbrae",
    "Belmont",
    "Breakwater",
    "Breamlea",
    "Buckley",
    "Burwood Heights",
    "Ballarat",
    "Benalla",
    "Bendigo",
    "Beechworth",
    "Bright",
    "Bairnsdale",
    "Bass",
    "Belgrave",
    "Berwick",
    "Broadford",
    "Cairo",
    "Chicago",
    "Cologne",
    "Copenhagen",
    "Casablanca",
    "Cape Town",
    "Calgary",
    "Cardiff",
    "Cambridge",
    "Chester",
    "Canterbury",
    "Cheltenham",
    "Coventry",
    "Crewe",
    "Carlisle",
    "Colchester",
    "Chichester",
    "Chesterfield",
    "Chorley",
    "Crawley",
    "Croydon",
    "Chatham",
    "Clacton",
    "Corby",
    "Cannock",
    "Camberley",
    "Chippenham",
    "Christchurch",
    "Cirencester",
    "Cleethorpes",
    "Coleraine",
    "Conwy",
    "Carmarthen",
    "Cardigan",
    "Caerphilly",
    "Cwmbran",
    "Chepstow",
    "Caerleon",
    "Caernarfon",
    "Carnforth",
    "Clitheroe",
    "Congleton",
    "Colne",
    "Cumbernauld",
    "Coatbridge",
    "Clydebank",
    "Cambuslang",
    "Carluke",
    "Cowdenbeath",
    "Cupar",
    "Campbeltown",
    "Castletown",
    "Carrickfergus",
    "Cookstown",
    "Craigavon",
    "Comber",
    "Carryduff",
    "Crossgar",
    "Castlewellan",
    "Cushendall",
    "Cushendun",
    "Carnlough",
    "Cloughmills",
    "Cullybackey",
    "Crumlin",
    "Carrickmore",
    "Castlederg",
    "Claudy",
    "Coalisland",
    "Carlow",
    "Cork",
    "Clonmel",
    "Cashel",
    "Cahir",
    "Carrickmacross",
    "Castlebar",
    "Charleville",
    "Clonakilty",
    "Cobh",
    "Courtmacsherry",
    "Crookhaven",
    "Crosshaven",
    "Carrigtwohill",
    "Castlelyons",
    "Conna",
    "Coachford",
    "Crookstown",
    "Castlemartyr",
    "Cloyne",
    "Carrigaline",
    "Carrignavar",
    "Charlotte",
    "Cincinnati",
    "Cleveland",
    "Columbus",
    "Chandler",
    "Cedar Rapids",
    "Chattanooga",
    "Charleston",
    "Chesapeake",
    "Cary",
    "Camden",
    "Clifton",
    "Concord",
    "Columbia",
    "Corona",
    "Clearwater",
    "Carrollton",
    "Centennial",
    "Carson",
    "Carlsbad",
    "Champaign",
    "Chico",
    "Cheyenne",
    "Clarksville",
    "Conway",
    "Cranston",
    "Cupertino",
    "Cypress",
    "Canton",
    "Casper",
    "Celina",
    "Centralia",
    "Centre",
    "Chadron",
    "Challis",
    "Chambersburg",
    "Chancellor",
    "Chanute",
    "Chardon",
    "Charlottesville",
    "Chatfield",
    "Cheboygan",
    "Chelan",
    "Chelsea",
    "Cherokee",
    "Cheverly",
    "Chickasha",
    "Childress",
    "Chillicothe",
    "Chino",
    "Choctaw",
    "Christiansburg",
    "Christmas",
    "Chubbuck",
    "Cicero",
    "Circleville",
    "Cisco",
    "Clackamas",
    "Clanton",
    "Claremont",
    "Clarendon",
    "Clarion",
    "Clarksburg",
    "Clayton",
    "Clearfield",
    "Cleburne",
    "Clemmons",
    "Clemson",
    "Climax",
    "Clinton",
    "Cloquet",
    "Clovis",
    "Coachella",
    "Coalinga",
    "Coatesville",
    "Cobleskill",
    "Cocoa",
    "Coffeyville",
    "Cohoes",
    "Collierville",
    "Collingswood",
    "Collins",
    "Collinsville",
    "Coloma",
    "Commerce",
    "Compton",
    "Conneaut",
    "Connecticut",
    "Conroe",
    "Coolidge",
    "Copiague",
    "Coppell",
    "Corbin",
    "Cordele",
    "Corinth",
    "Coronado",
    "Corrigan",
    "Corsicana",
    "Cortez",
    "Cortland",
    "Corvallis",
    "Cotton",
    "Cottonwood",
    "Covina",
    "Covington",
    "Cranberry",
    "Cranford",
    "Crawford",
    "Cresskill",
    "Crestview",
    "Crestwood",
    "Crookston",
    "Crossville",
    "Crystal",
    "Cudahy",
    "Cumberland",
    "Cadillac",
    "Cameron",
    "Campbell",
    "Canandaigua",
    "Canonsburg",
    "Carbondale",
    "Caribou",
    "Carmel",
    "Carnegie",
    "Carpentersville",
    "Cartersville",
    "Casselberry",
    "Cedar Hill",
    "Cerritos",
    "Chanhassen",
    "Chantilly",
    "Cheektowaga",
    "Chesterton",
    "Cicero",
    "Citrus Heights",
    "Coon Rapids",
    "Cutler Bay",
    "Cuyahoga Falls",
    "Calexico",
    "Calumet",
    "Canoga Park",
    "Capitola",
    "Castro Valley",
    "Cedar Falls",
    "Cedar Park",
    "Ceres",
    "Cairns",
    "Caloundra",
    "Camberwell",
    "Campbelltown",
    "Canberra",
    "Carlingford",
    "Carlton",
    "Carnegie",
    "Carrum",
    "Casey",
    "Castlemaine",
    "Caulfield",
    "Cessnock",
    "Charlestown",
    "Chatswood",
    "Cheltenham",
    "Cherrybrook",
    "Clayton",
    "Clontarf",
    "Coburg",
    "Cockatoo",
    "Colac",
    "Collaroy",
    "Collingwood",
    "Como",
    "Condell Park",
    "Coogee",
    "Cook",
    "Coonabarabran",
    "Cooranbong",
    "Coowangup",
    "Cornubia",
    "Corrimal",
    "Cowra",
    "Craigieburn",
    "Cranbourne",
    "Cremorne",
    "Cronulla",
    "Curl Curl",
    "Currimundi",
    "Caboolture",
    "Caracas",
    "Cartagena",
    "Chihuahua",
    "Cordoba",
    "Cusco",
    "Curitiba",
    "Concepcion",
    "Cali",
    "Camaguey",
    "Cochabamba",
    "Corrientes",
    "Catamarca",
    "Colon",
    "Cartago",
    "Chimbote",
    "Cajamarca",
    "Chiclayo",
    "Callao",
    "Cagua",
    "Cabudare",
    "Cabimas",
    "Cumana",
    "Chacao",
    "Carrizal",
    "Charallave",
    "Coro",
    "Carora",
    "Caucagua",
    "Caripe",
    "Chivacoa",
    "Calabozo",
    "Carupano",
    "Clarines",
    "Cabure",
    "Chichiriviche",
    "Churuguara",
    "Cafetal",
    "Caribe",
    "Cardon",
    "Catoche",
    "Chaguaramas",
    "Chabasquen",
    "Chama",
    "Chejende",
    "Chinacota",
    "Chorrera",
    "Chuao",
    "Colonia",
    "Coromoto",
    "Cumarebo",
    "Curiepe",
    "Chicoutimi",
    "Cornwall",
    "Cranbrook",
    "Chilliwack",
    "Courtenay",
    "Collingwood",
    "Cobourg",
    "Chateauguay",
    "Cold Lake",
    "Camrose",
    "Canmore",
    "Cochrane",
    "Chestermere",
    "Coaldale",
    "Consort",
    "Coleman",
    "Cardston",
    "Claresholm",
    "Creston",
    "Cumberland",
    "Castlegar",
    "Chase",
    "Clinton",
    "Clearwater",
    "Chetwynd",
    "Coquitlam",
    "Comox",
    "Colwood",
    "Cassiar",
    "Carmacks",
    "Cabri",
    "Canora",
    "Carnduff",
    "Churchbridge",
    "Climax",
    "Coronach",
    "Creighton",
    "Cudworth",
    "Carman",
    "Churchill",
    "Camperville",
    "Cartwright",
    "Clandeboye",
    "Carberry",
    "Carmen",
    "Crossfield",
    "Calmar",
    "Carstairs",
    "Caroline",
    "Cremona",
    "Cessford",
    "Champion",
    "Chinook",
    "Chauvin",
    "Coronation",
    "Czar",
    "Carcross",
    "Champagne",
    "Chicken",
    "Circle",
    "Central",
    "Chalkyitsik",
    "Chefornak",
    "Chevak",
    "Chignik",
    "Chitina",
    "Chistochina",
    "Chugiak",
    "Coffman Cove",
    "Coldfoot",
    "Cordova",
    "Craig",
    "Cantwell",
    "Chatanika",
    "Castor",
    "Cereal",
    "Coalhurst",
    "Crowsnest Pass",
    "Cannes",
    "Caen",
    "Calais",
    "Cannes",
    "Carcassonne",
    "Châlons-en-Champagne",
    "Chambéry",
    "Chartres",
    "Châteauroux",
    "Cherbourg",
    "Clermont-Ferrand",
    "Colmar",
    "Compiègne",
    "Créteil",
    "Chemnitz",
    "Cottbus",
    "Celle",
    "Coburg",
    "Constance",
    "Cuxhaven",
    "Catania",
    "Cremona",
    "Como",
    "Chieti",
    "Campobasso",
    "Caserta",
    "Carrara",
    "Cesena",
    "Civitavecchia",
    "Conegliano",
    "Cortona",
    "Cosenza",
    "Cuneo",
    "Córdoba",
    "Cádiz",
    "Castellón",
    "Ceuta",
    "Cuenca",
    "Ciudad Real",
    "Cartagena",
    "Cáceres",
    "Coimbra",
    "Castelo Branco",
    "Chaves",
    "Caldas da Rainha",
    "Covilhã",
    "Cluj-Napoca",
    "Constanța",
    "Craiova",
    "Călărași",
    "Câmpina",
    "Caracal",
    "Caransebeș",
    "Cernavodă",
    "Codlea",
    "Comănești",
    "Corabia",
    "Costești",
    "Câmpulung",
    "Chișinău",
    "Cahul",
    "Cantemir",
    "Căușeni",
    "Ceadîr-Lunga",
    "Chernobyl",
    "Cherkasy",
    "Chernivtsi",
    "Chernihiv",
    "Chervonohrad",
    "Chornomorsk",
    "Chuhuiv",
    "Czyżewo",
    "Częstochowa",
    "Chełm",
    "Chorzów",
    "Cieszyn",
    "Ciechanów",
    "Chojna",
    "Chełmno",
    "Chrzastowice",
    "Czechowice-Dziedzice",
    "Czerwionka-Leszczyny",
    "Chelyabinsk",
    "Cheboksary",
    "Chita",
    "Cherkessk",
    "Chernyakhovsk",
    "Chapayevsk",
    "Chistopol",
    "Chusovoy",
    "Chaikovsky",
    "Chernushka",
    "Chernogorsk",
    "Chuguev",
    "Chusovaya",
    "Chunsky",
    "Cherkizovo",
    "Chernorechensk",
    "Chudovo",
    "Chusovskoy",
    "Cairo",
    "Cape Town",
    "Casablanca",
    "Constantine",
    "Conakry",
    "Cotonou",
    "Cotonco",
    "Cabinda",
    "Cuito",
    "Caxito",
    "Caála",
    "Camacupa",
    "Caluquembe",
    "Catabola",
    "Catchiungo",
    "Cazombo",
    "Chiange",
    "Chibia",
    "Chicala",
    "Chifunde",
    "Chinguar",
    "Chitado",
    "Chiúme",
    "Chókwè",
    "Cuamba",
    "Cubal",
    "Cucumbi",
    "Cuemba",
    "Cufada",
    "Cuíto",
    "Culango",
    "Cuvelai",
    "Chennai",
    "Chandigarh",
    "Coimbatore",
    "Cuttack",
    "Cochin",
    "Calicut",
    "Chandigarh",
    "Chittoor",
    "Cuddalore",
    "Chengalpattu",
    "Chidambaram",
    "Chingleput",
    "Chitradurga",
    "Chikmagalur",
    "Coorg",
    "Cannanore",
    "Cuddapah",
    "Chittorgarh",
    "Churu",
    "Chamba",
    "Changlang",
    "Champhai",
    "Churachandpur",
    "Chandel",
    "Chengdu",
    "Chongqing",
    "Changchun",
    "Changsha",
    "Changzhou",
    "Chengde",
    "Chifeng",
    "Cangzhou",
    "Changzhi",
    "Chenzhou",
    "Chaoyang",
    "Chizhou",
    "Chuzhou",
    "Chuxiong",
    "Changji",
    "Changde",
    "Changning",
    "Chaohu",
    "Chengmai",
    "Changle",
    "Chiping",
    "Changfeng",
    "Changge",
    "Changyi",
    "Changtai",
    "Changshan",
    "Changxing",
    "Changyuan",
    "Chaozhou",
    "Chenbaerhu",
    "Chenggu",
    "Chengkung",
    "Chenzhou",
    "Chiayi",
    "Chiba",
    "Chigasaki",
    "Chitose",
    "Chofu",
    "Choshi",
    "Chatan",
    "Chikusei",
    "Chichibu",
    "Choushi",
    "Canberra",
    "Cairns",
    "Caloundra",
    "Camberwell",
    "Camden",
    "Campbelltown",
    "Canterbury",
    "Carlingford",
    "Carlton",
    "Carnegie",
    "Carrum",
    "Casey",
    "Castle Hill",
    "Castlemaine",
    "Caulfield",
    "Cessnock",
    "Charlestown",
    "Chatswood",
    "Chelsea",
    "Cheltenham",
    "Cherrybrook",
    "Clayton",
    "Clemton Park",
    "Clontarf",
    "Coburg",
    "Cockatoo",
    "Colac",
    "Collaroy",
    "Collingwood",
    "Como",
    "Concord",
    "Condell Park",
    "Coogee",
    "Cook",
    "Coonabarabran",
    "Cooranbong",
    "Coowangup",
    "Cornubia",
    "Corrimal",
    "Cowra",
    "Craigieburn",
    "Cranbourne",
    "Cremorne",
    "Cronulla",
    "Croydon",
    "Curl Curl",
    "Currimundi",
];
